### ISSUE TITLE
Add support to install additional libraries/drivers in Windows

### ISSUE THREAD

**Issue by marcopiraccini** [electron/windows-installer#10]
Hi, 
I'm creating an electron app that uses a printer, and I'd like to install the printer driver along with the application (in Windows). 
Of course, the driver can be installed manually, but I want to reduce the number of things that user must do. 
Is that possible?

**Comment by paulcbetts** [comment]
This isn't easily possible with Squirrel because it requires you to be an elevated administrator, and Squirrel explicitly tries its best to run as a normal user. I would make your app on `--squirrel-firstrun` install the printer driver

**Comment by TemaSM** [comment]
@marcopiraccini Yeah, that's possible, but it must be done by yourself not by `windows-installer` or Squirrel.
You can install drivers by manual execution of `dpinst.exe` with special arguments.
Some docs (Googled): 
([#1](https://msdn.microsoft.com/en-us/library/windows/hardware/ff544842%28v=vs.85%29.aspx?f=255&MSPPError=-2147217396)) ([#2](https://msdn.microsoft.com/en-us/library/windows/hardware/ff544775(v=vs.85).aspx)) ([#3](http://www.itninja.com/blog/view/dpinst-exe-silent-install-drivers))
Remember, probably your app will need Admin rights (UAC) for installing drivers.
And don't forget, that you able to use C++ native modules with bindings to Node.
Alternatively, have a look at [(GitHub) DriverPack-Solution](https://github.com/DriverPackSolution/DriverPack-Solution), it's so similar to JS.

**Comment by vicentedealencar** [comment]
maybe this helps https://github.com/tjanczuk/edge

**Comment by marcopiraccini** [comment]
Well, the combined use of:

- custom template to copy .cmd and the driver files (when available) 
- dpinst
- manage --squirrel-firstrun to use dpinst

...should do the job.

**Comment by develar** [comment]
electron-builder 3.0.1 allows you to copy extra resources to app.
