### ISSUE TITLE
Change extension of template.nuspec

### ISSUE THREAD

**Issue by JakeGinnivan** [electron/windows-installer#100]
I am using Octopus Deploy to package my electron app, then as part of the deploy I build an installer for the environment I am deploying to.

This works great except for the fact that NuGet strips out any *.nuspec files by default. NuGet 3.3 fixed this as far as I can see in https://github.com/NuGet/Home/issues/439 but Octo.exe which packages up my installer must not be that up to date.

Any chance you could rename it to `template.nuspectemplate` or something to get around this issue?

**Comment by BenVanZyl** [comment]
I have made this change and we tested it successfully in our environment.  I would like to push this up and create the PR but I am getting a permissions denied error.  I can pull code but I am unable to push the code updates.

Command:
_git push --set-upstream origin Change-template-nuspec-To-template-nuspectemplate_

Reply:
_remote: Permission to electron/windows-installer.git denied to BenVanZyl.
fatal: unable to access 'https://github.com/electron/windows-installer.git/': The requested URL returned error: 403_

How do I proceed to get this fix into the build?

Thanks.

**Comment by JakeGinnivan** [comment]
hey @BenVanZyl 

You need to fork this repository, then you can push your changes into your fork and submit a PR from there. This flow means that only the core contributors need write permission to the main repo. If you have a read of https://help.github.com/articles/fork-a-repo/ then https://help.github.com/articles/using-pull-requests/ that should point you in the right direction.

**Comment by BenVanZyl** [comment]
Thanks.. Will give it a go.

**Comment by BenVanZyl** [comment]
The PR is up for review and ready to be merged.

https://github.com/electron/windows-installer/pull/114

**Comment by MarshallOfSound** [comment]
Merged in #114

**Comment by BenVanZyl** [comment]
Thanks
