### ISSUE TITLE
Why it always start up my app twice?

### ISSUE THREAD

**Issue by yeluoqiuzhi** [electron/windows-installer#102]
It always startup my app twice.
when the install process finish half of work(It showed the installing gif), "my app" start once,
then,it close "my app" and start it twice when finish the install process.

**Comment by MarshallOfSound** [comment]
Doesn't anyone read the README's anymore :cry: 

https://github.com/electron/windows-installer#handling-squirrel-events

**Comment by yeluoqiuzhi** [comment]
I see it. this is the reason why it start my app again,when I uninstall it.Thank you.😇
