### ISSUE TITLE
RELEASES file.

### ISSUE THREAD

**Issue by tvolpatto** [electron/windows-installer#103]
What is the last number in the RELEASES file?

D708CF6D46A5C953EFE8ECEAA2EB1BF78CB36C1A MyApp-0.1.1-full.nupkg **49853775**
Its randomic? Some kind of timestamp? Cause I want to read and compare two RELEASES.

**Comment by MarshallOfSound** [comment]
Pretty sure it is file size

**Comment by tvolpatto** [comment]
Thanks man!
