### ISSUE TITLE
delta nupkg question with remoteReleases

### ISSUE THREAD

**Issue by shimika** [electron/windows-installer#104]
I have a 3 versions.

If I build 0.1 -> create 0.1-full.nupkg
If I build 0.2 -> create 0.1-full.nupkg, 0.2-full.nupkg, 0.2-delta.nupkg.
If I build 0.3 -> create 0.1-full.nupkg, 0.2-full.nupkg, 0.3-full.nupkg 0.2-delta.nupkg 0.3-delta.nupkg

Is it right?
I think it is too much files and totally huge file size to upload github...

**Comment by MarshallOfSound** [comment]
I think you misunderstand what is going on.

Build 0.1 -> Create 0.1-full.nupkg
Build 0.2 -> Create 0.2-full.nupkg, 0.2-delta.nupkg
Build 0.3 -> Create 0.3-full.nupkg, 0.3-delta.nupkg

At each step you are generating two files, one containing your entire app and one containing deltas between it and the previous version.  You aren't regenerating / making new nupkg's for the old version each time

**Comment by shimika** [comment]
Let me show my route.

1. I build 0.1 version,  app-0.1-full.nupkg.
2. I upload app-0.1-full.nupkg + RELEASES file (2 files.)
3. I build 0.2 version, app-0.1-full.nupkg + app-0.2-full.nupkg + app-0.2-delta.nupkg generated.
    (It is strange but ok)
4. I upload app-0.2-full.nupkg + app-0.2-delta.nupkg + RELEASES file (3 files).
5. I build 0.3 version, 
-> Problem: app-0.1-full.nupkg + app-0.2-full.nupkg + app-0.2-delta.nupkg, app-0.3-full.nupkg, app-0.3-delta.nupkg generated.

I don't want to generate old version's full nupkg but this module generate all of version's nupkg.
Is it problem to my route?

**Comment by shimika** [comment]
I upload to github like this.

<img width="478" alt="capture" src="https://cloud.githubusercontent.com/assets/4963314/15998508/db87fa78-3179-11e6-875a-e05624fe2ac5.PNG">

**Comment by shimika** [comment]
I upload to github like this.

<img width="537" alt="capture" src="https://cloud.githubusercontent.com/assets/4963314/15998554/29ecdf80-317a-11e6-8b05-e506b700933d.PNG">

**Comment by MarshallOfSound** [comment]
@shimika Your upload is correct, however your assumption that you are GENERATING the old `nupkg` files is incorrect.  This tool downloads them for you from your `remote-releases` URL.

It then uses those files to generate the deltas.  It isn't generating them, it is just downloading them

**Comment by MarshallOfSound** [comment]
Closing as I'm pretty sure this question has been answered
