### ISSUE TITLE
Creating a installer... Tiny gif animation?

### ISSUE THREAD

**Issue by ErraticFox** [electron/windows-installer#105]
So I created a installer, opened the .exe and it opened my program, not a installer. Played a little green gif in the middle, then reopened the program once the gif was done... I thought this was like a installer where you choose where you wanted it installed and if you want a desktop icon, etc.

**Comment by develar** [comment]
If you use https://github.com/electron-userland/electron-builder, that there is a good news — NSIS support is coming if you prefer "standard" installer. 

But I recommend to use Squirrel.Windows because for most of the users Squirrel installer is a better than a boring installer procedure (click -> click -> ok).

**Comment by MarshallOfSound** [comment]
The simplist response to this is

You thought wrong 😆 

Squirrel is Click Once but it works.  I.e. no user iteraction, it just installs and you are ready to rock and roll.

**Comment by develar** [comment]
@MarshallOfSound Yep. And if for some user is it really required to install it to custom location, setup.exe can be just unzipped to any location (twice unzip).

**Comment by ErraticFox** [comment]
But where does it even install? No choice to add to desktop icon? It doesn't even show up as recently installed.

**Comment by develar** [comment]
@ErraticFox Clearly stated in the readme — https://github.com/electron/windows-installer#handling-squirrel-events — "Install desktop and start menu shortcuts"

**Comment by MarshallOfSound** [comment]
@ErraticFox As for 

> But where does it even install?

It installs to your `%APPDATA%` directory and it appears in Control Panel under "Installed Programs"

**Comment by MarshallOfSound** [comment]
Original question has been answered
