### ISSUE TITLE
Warning! Trojan Dropper in core.min.js

### ISSUE THREAD

**Issue by space-curiosity** [electron/windows-installer#106]
I found couple Trojan and Trojan Dropper inside node modules when you do npm install on projects and here is details:

node_modules\electron-winstaller-fixed\vendor\winterop.dll -> Trojan.Win32.Dropper.bgbb
node_modules\electron-winstaller-fixed\vendor\Setup.exe -> TrojanDropper.VBS.fand Trojan[:HEUR]/Win32.AGeneric

Please fix those issues.

**Comment by develar** [comment]
This module is from electron-builder. See AppVeyour — https://ci.appveyor.com/project/develar/squirrel-windows/build/1.0.35/artifacts Please report to electron-builder.

**Comment by develar** [comment]
Well, electron-builder uses the same files —https://github.com/develar/windows-installer/tree/builder/vendor, so, this issue should be addressed in this repository.

**Comment by MarshallOfSound** [comment]
To be honest, these kinds of false positives are sadly common in open source development.  There's probably not much that can be done to fix this without contacting the company that's reporting the false-positives and getting them to fix it 👍

**Comment by paulcbetts** [comment]
winterop.dll is from WiX and Setup.exe is the template EXE for Squirrel.Windows. Sadly, it's actually not super easy to distinguish between a dropper and a valid installer (i.e. we do all the same things a malware installer does, except we have the consent of the user)

**Comment by havenchyk** [comment]
Not an issue, as I see.
