### ISSUE TITLE
License of splash gif

### ISSUE THREAD

**Issue by develar** [electron/windows-installer#107]
I want to reuse https://github.com/electron/windows-installer/blob/master/resources/install-spinner.gif in my NSIS installer (wrapper and separate installer). Is it legal?

**Comment by paulcbetts** [comment]
@develar It's legal (it's from Atom), but really we should get rid of it because it makes zero sense

**Comment by develar** [comment]
No sense? If operation takes more than 4 seconds, we should somehow indicate progress. Task bar icon progress is not enough (in any case it is not implemented in Squiirel). Right? I don't see alternative. Or do you mean that we should add real progress bar?
