### ISSUE TITLE
Signing a Windows app

### ISSUE THREAD

**Issue by jsloyer** [electron/windows-installer#109]
I was looking at the [options to sign a windows app](https://github.com/electron/windows-installer/blob/12bce30ac261a04e0eb5eed665c1c927b6a6e06c/src/index.js#L159).  Does this sign just the `.exe` and `.msi` or does it sign your executable and `update.exe`

Also what is the suggested items to sign as well?

**Comment by paulcbetts** [comment]
It signs all of your executables and update.exe, then signs the outer MSI/EXE

**Comment by drjasonharrison** [comment]
Is it possible to sign the update.exe with a different tool? We have an enterprise application signing tool that keeps certificates off of our development machines.
