### ISSUE TITLE
Request: Clean up app data directories on uninstall

### ISSUE THREAD

**Issue by MarshallOfSound** [electron/windows-installer#113]
Currently when you uninstall a Squirrel app it levaes behind it's AppData directory with quite a bit of data which means a uninstall -> reinstall is not a clean install.

It would be better if it deleted those AppData folders and their contents on uninstall as that would kind of be expected of an uninstall.

Trying to implement this in JS with the Squirrel hooks results in file is locked errors (as you are trying to delete files that are in use).

**Comment by develar** [comment]
+1 (I haven't check, really, Doesn't Squirrel.Windows remove app data on uninstall?) But I guess that issue should be opened in the Squirrel.Windows issue tracker.

BTW, electron-builder NSIS uninstaller deletes app data on uninstall.

Code: https://github.com/Squirrel/Squirrel.Windows/blob/master/src/Squirrel/UpdateManager.ApplyReleases.cs#L92 Not yet checked, but it seems, yes, Squirrel doesn't remove app data folder.

**Comment by wangxiexe** [comment]
+1 for having this feature as default.  So at this moment any idea is there any api I can delete that data folder in uninstall event handler?

**Comment by MarshallOfSound** [comment]
@wangxiexe 

```js
require('rimraf').sync(require('electron').app.getPath('userData'));
```

Inside the `--squirrel-uninstall` event

**Comment by wangxiexe** [comment]
@MarshallOfSound  actually I tried this but what I notice is that if I did not close my app when run uninstall, uninstall does not work at all. 

I guess when the app is running, the userdata directory is being used so rimraf failed

I also tried calling app.quit() before that statement, it did not help either..

**Comment by andymartinwork** [comment]
@wangxiexe 

The optimal situation for this would be for the app to inform the other running instances of the app to quit. I tried it using the app api but couldn't make it work.

The hacky solution was to put a try catch around the rimraf command.

**Comment by ianrtracey** [comment]
+1 on this. Currently using the installer on a project and users were startled to see the userData directory still populated with files. I can take a stab at this if the issue is still open.

**Comment by ianrtracey** [comment]
Going to take a stab at this.

**Comment by topched** [comment]
@ianrtracey Did you ever come up with a solution for this? Currently stuck on the same problem and nothing seems to work.

**Comment by ianrtracey** [comment]
Got bogged down. Will take a look at this this weekend @topched .

**Comment by karthik-gumpu** [comment]
I am also facing the same issue. Any solution?

**Comment by MarshallOfSound** [comment]
I provided a solution to this issue a few comments in, see https://github.com/electron/windows-installer/issues/113#issuecomment-240102950

**Comment by locpv-ibl** [comment]
any updated? I'm facing the same issue too.

**Comment by karthik-gumpu** [comment]
I removed preferences file(which contains all logged in user data) from app data like below on squirrel uninstall event.

//Remove local preferences file
rimraf.sync(path.join(app.getPath('userData'),'pref.json'),null,function(error){
     if(error){
	log.error(err);
     }
});

**Comment by info-ankit** [comment]
Any Updates!! Still i am facing same issue - 
```
require('rimraf').sync(require('electron').app.getPath('userData'));
```
Inside the --squirrel-uninstall event

**Comment by Vashkatsi** [comment]
> @wangxiexe
> 
> ```js
> require('rimraf').sync(require('electron').app.getPath('userData'));
> ```
> 
> Inside the `--squirrel-uninstall` event

Can`t find how to set `--squirrel-uninstall`, can you show example, please.

**Comment by balamgithub** [comment]
> > @wangxiexe
> > ```js
> > require('rimraf').sync(require('electron').app.getPath('userData'));
> > ```
> > 
> > 
> > Inside the `--squirrel-uninstall` event
> 
> Can`t find how to set `--squirrel-uninstall`, can you show example, please.

Go to "test-app-one" project inside electron-builder git source repo.

**Comment by Lob2018** [comment]
> 
> 
> I provided a solution to this issue a few comments in, see [#113 (comment)](https://github.com/electron/windows-installer/issues/113#issuecomment-240102950)

Hello  @MarshallOfSound

With the workaround for main.js, at the end of [Squirrel.Windows - Electron Forge](https://www.electronforge.io/config/makers/squirrel.windows#my-app-is-launching-multiple-times-during-install) :
```javascript
const { app } = require('electron');
if (require('electron-squirrel-startup')) return app.quit();
```
**When we uninstall the App, nothing is removed from Usr\AppData\Local\AppName**
It could be great to specify this with this workaround...

But in the main.js when we use [Handling Squirrel Events](https://github.com/electron/windows-installer#handling-squirrel-events) :
```javascript
const { app } = require('electron');
// this should be placed at top of main.js to handle setup events quickly
if (require('electron-squirrel-startup')) return;
if (handleSquirrelEvent()) {
    // squirrel event handled and app will exit in 1000ms, so don't do anything else
    return;
}
function handleSquirrelEvent() {
    if (process.argv.length === 1) {
        return false;
    }
    const ChildProcess = require('child_process');
    const path = require('path');
    const appFolder = path.resolve(process.execPath, '..');
    const rootAtomFolder = path.resolve(appFolder, '..');
    const updateDotExe = path.resolve(path.join(rootAtomFolder, 'Update.exe'));
    const exeName = path.basename(process.execPath);
    const spawn = function(command, args) {
        let spawnedProcess, error;
        try {
            spawnedProcess = ChildProcess.spawn(command, args, { detached: true });
        } catch (error) {}
        return spawnedProcess;
    };
    const spawnUpdate = function(args) {
        return spawn(updateDotExe, args);
    };
    const squirrelEvent = process.argv[1];
    switch (squirrelEvent) {
        case '--squirrel-install':
        case '--squirrel-updated':
            // Optionally do things such as:
            // - Add your .exe to the PATH
            // - Write to the registry for things like file associations and
            //   explorer context menus
            // Install desktop and start menu shortcuts
            spawnUpdate(['--createShortcut', exeName]);
            setTimeout(app.quit, 1000);
            return true;
        case '--squirrel-uninstall':
            // Undo anything you did in the --squirrel-install and
            // --squirrel-updated handlers
            // Remove desktop and start menu shortcuts
            spawnUpdate(['--removeShortcut', exeName]);
            setTimeout(app.quit, 1000);
// * require('rimraf').sync(require('electron').app.getPath('userData'));
            return true;
        case '--squirrel-obsolete':
            // This is called on the outgoing version of your app before
            // we update to the new version - it's the opposite of
            // --squirrel-updated
            app.quit();
            return true;
    }
};
```
Most of the files in Usr\AppData\Local\AppName are deleted (only keep Update.exe and .dead).

I failed to get the rimraf module to work at the line :
 ```javascript
// * require('rimraf').sync(require('electron').app.getPath('userData'));
```
Where do you use it ?

**Comment by paragdulam** [comment]
Lets say the electron windows app is installed on a windows machine which has multiple windows users(Administrator and other user accounts).

        "nsis": {
            "deleteAppDataOnUninstall": true,
            "oneClick": false
        }

I have deleteAppDataOnUninstall to true in package.json.

Issue:
The app data gets deleted from the user who uninstalled the app. e.g. if a non-admin account uninstalls the app from Control Panel, that user's appData gets deleted but NOT OF OTHERS.

When the app is reinstalled, Other windows accounts wont get a fresh newly installed app. The one who uninstalled the app only that user account gets a newly installed app. 

How can we delete all the app user data for all accounts when app is uninstalled?

**Comment by SnehalJ1509** [comment]
> Lets say the electron windows app is installed on a windows machine which has multiple windows users(Administrator and other user accounts).
> 
> ```
>     "nsis": {
>         "deleteAppDataOnUninstall": true,
>         "oneClick": false
>     }
> ```
> 
> I have deleteAppDataOnUninstall to true in package.json.
> 
> Issue:
> The app data gets deleted from the user who uninstalled the app. e.g. if a non-admin account uninstalls the app from Control Panel, that user's appData gets deleted but NOT OF OTHERS.
> 
> When the app is reinstalled, Other windows accounts wont get a fresh newly installed app. The one who uninstalled the app only that user account gets a newly installed app.
> 
> How can we delete all the app user data for all accounts when app is uninstalled?
> @MarshallOfSound

@paragdulam Thank you for your solution! It works as expected in Windows. Do you or anyone have any idea if anything similar is available for MacOS? I am creating a .dmg and then installing the app via it.

**Comment by JerryI** [comment]
Bump. No such option is available on MacOS

PS: I am using electron-builder
