### ISSUE TITLE
Wrong shortcut name

### ISSUE THREAD

**Issue by matiastucci** [electron/windows-installer#115]
I'm packaging my app with `electron-packager` and setting the name with the `appname` flag like this: `--appname="myApp"`. This is generating a `myApp.exe` file, but then when I ran:

```
const resultPromise = electronInstaller.createWindowsInstaller({
  title: 'TelemetryTV',
  appDirectory: './releases/windows/myApp',
  outputDirectory: outputDirectory,
  authors: 'myApp',
  exe: 'myApp.exe'
});
```

and ran the `setup.exe` is creating a shortcut in my desktop but with `Electron` as a name. I'm not sure if I'm doing something wrong of it's a bug. Any ideas?

Thanks!

**Comment by matiastucci** [comment]
I needed to pass `--version-string.ProductName="myApp"` to the `electron-packager`

**Comment by dstj** [comment]
In case someone stumbles on this, the current `electron-packager` setting is now called `win32metatadata` instead of `version-string`:

```
--win32metadata.ProductName=\"Your App Name\" --win32metadata.CompanyName=\"Your company\" 
```
