### ISSUE TITLE
The application built by windows-installer restarts

### ISSUE THREAD

**Issue by soichih** [electron/windows-installer#121]
Hello. Thanks for this great app! So far this is the only electron windows installer builder that actually works!! (well, sort of..)

I have a helloworld electron app that I've built using electron-packager, and then built an .exe file using windows-installer. When I launch the .exe, it does following on Windows 10.

1) Shortly after double clicking the .exe, it displays a green-ish splash animation showing something like a cartoonist text editor (I think it's just a default splash screen .gif animation?)
2) After 5-10 seconds, the splash screen goes away, and I see my helloworld app window, and I can interact with it. However, I still see windows-installer .exe loading in the background (showing progress on the task icon)
3) After 15-20 seconds, the windows-installer .exe finish loading(?), and my initial helloworld app is terminated, and immediately after that, another instance of my hello world app gets started. 

Why do I see my app prematurely(?) started and getting killed shortly after everything is loaded?

--------------

The reason why I am using windows-installer to launch my electron app is that, in order to distribute my app (built by electron-packager) I still need to zip the entire directory generated by electron-packager. Unzipping any zip file on Windows is extremely slow (maybe due to the virus protection?) so distributing my app in .zip format is not an option. I am hoping that I can distribute a single .exe file generated by windows-installer so that user can launch *it* to start my app.. If there is a better way to accomplish this, please let me know!

**Comment by MarshallOfSound** [comment]
Please read the Squirrel Events section of the README 👍 

https://github.com/electron/windows-installer#handling-squirrel-events

**Comment by soichih** [comment]
Thanks!

**Comment by jacktang** [comment]
@soichih do you fix the problem finally?
@MarshallOfSound I face the same problem as soichih described. And I have handled squirrel events in main-process (learned from google-music-player project). Could you please share the tips on how to fix the problem? Thanks a lot!
