### ISSUE TITLE
Unable to find setupIcon

### ISSUE THREAD

**Issue by jsloyer** [electron/windows-installer#123]
I am getting a weird issue when running this through the Gruntask.  Here is the relavent bits.

```
grunt.initConfig({
        'create-windows-installer': {
            ia32: {
                appDirectory: '../product',
                outputDirectory: '../product',
                authors: 'Company',
                exe: 'myexe.exe',
                title: 'Myapp',
                setupIcon: 'resources/win32/app.ico',
            }
        },
```

I get the following:

```
Warning: Failed with exit code: 1
Output:
Fatal error: Unable to load file
 Use --force to continue.
```

Running the command via command line works fine and doesn't return any errors.

Any ideas?

**Comment by mzmousa** [comment]
Could it be that you only have the `grunt-cli` but not the `grunt task runner`? Have you done a 
```npm install grunt --save-dev``` in your project directory with the grunt task? I looked here:

http://stackoverflow.com/questions/15483735/fatal-error-unable-to-find-local-grunt-when-running-grunt-command

**Comment by jsloyer** [comment]
@mzmousa yeah I already have grunt saved as a dev dependency.

**Comment by MarshallOfSound** [comment]
Hey 👋 

This issue is being closed as it is stale.  This normally means that the issue has been fixed in newer versions or this issue or no longer impacting you.  If this is not the case please feel free to comment with and @ mention me and we can revisit this.

**Comment by MarshallOfSound** [comment]
_note for anyone finding this issue_

This is probably caused by `setupIcon` not being an absolute path, use `path.resolve` to get an absolute path and this should work flawlessly 👍

**Comment by TTATPuOT** [comment]
> 
> 
> _note for anyone finding this issue_
> 
> This is probably caused by `setupIcon` not being an absolute path, use `path.resolve` to get an absolute path and this should work flawlessly 👍

Same error.
I'm using 
`E:\Storm Projects\Web\photo-uploader-v2\public\icons\icon.ico` and `D:\icon.ico` - it's fails by this error.

**Comment by lockiechen** [comment]
any solution?
