### ISSUE TITLE
Windows 10 Enabling Win32 Long Path Support

### ISSUE THREAD

**Issue by Unforgiven-wanda** [electron/windows-installer#129]
Hello,
Now that anniversary update is available, I was hoping that enabling this new feature (see https://blogs.msdn.microsoft.com/jeremykuhne/2016/07/30/net-4-6-2-and-long-paths-on-windows-10/) would allow us to build without hassle on Windows. However in my case I do still get the `System.IO.PathTooLongException` error whenever my node_modules goes a bit too deep.

I'm not too knowledgeable about the subject, but is there some plan to take advantage of this feature in the near future?

Thank you.

**Comment by develar** [comment]
@Unforgiven-wanda Just enable `asar`. I see your issue — https://github.com/electron-userland/electron-builder/issues/686 Well, you can spend a lot of time to " already gone through the process of packaging my app" or just use electron-builder, electron-builder has suitable correct defaults. e.g. asar is enabled by default and native deps are extracted automatically without any configuration on your side.

**Comment by MarshallOfSound** [comment]
@Unforgiven-wanda As @develar ASAR gets around these issues, also using `npm 3.x+` can resolve a lot of these deep path issues.

However I don't see how this is a `windows-installer` issue. From a brief glance at that linked page I see the following.

> Long paths aren’t enabled by default yet. You need to set a policy to enable the support. To do this you want to “Edit group policy” in the Start search bar or run “gpedit.msc” from the Run command (Windows-R).

I don't think we can or should support a system which could build and install on one machine and fail on another.  Until that long path option becomes default IMO we shouldn't support it, especially if it requires a group policy to make it work.

In the meantime use ASAR packaging techniques to get around the path restrictions
