### ISSUE TITLE
Downloading old releases for delta

### ISSUE THREAD

**Issue by solgarius** [electron/windows-installer#130]
I have a question about the downloads of old releases for creating delta files on windows builds. As far as I can tell whenever I do a build the windows-installer (via electron-builder) downloads all of the previous releases to create the latest delta and as each .nupkg release is ~65mb in our system, that means every release the amount that needs to be downloaded is getting much larger.

For example to calculate the deltas: 
build release 1.0.0, to calculate delta doesn't download anything
build release 1.0.1, downloads 1.0.0 ~65mb (total 65mb)
build release 1.0.2, downloads 1.0.1 ~65mb + 1.0.1.delta ~1mb or so, + 1.0.0 ~65mb (total 131mb)
build release 1.0.3, downloads: 1.0.2, 1.0.2.delta, 1.0.1, 1.0.1.delta, 1.0.0 (total ~197mb)
etc etc

Even after 4 releases the build is starting to take quite a while as it downloads many files that appear unnecessary.

Is there a point where it stops downloading every version, and why does it need to download more than just the most recent release? i.e. when doing 1.0.3 why does it need 1.0.1 and 1.0.0?

My setup is downloading from a github private repository, same repository that it pushes the release to when completed. Also my build script will wipe the build directory before starting (although even if my script doesn't wipe the directory I believe either electron-builder or windows-installer wipes the "win" and "win-unpacked" folders anyway)

Also note, our repository is used to only store releases and does not contain any code etc in the repository itself. We do this due to security restrictions on the github token and access to the raw source code. I'm not sure if this might be an issue.

I'm not sure if I am perhaps setting up the build incorrectly?

Also note this issue was first raised on electron-builder: [https://github.com/electron-userland/electron-builder/issues/685](https://github.com/electron-userland/electron-builder/issues/685)

**Comment by patricksebastien** [comment]
I have the same issue. What are we doing wrong.
@solgarius did you find a solution?

**Comment by solgarius** [comment]
@patricksebastien  I never really found a solution, except that it sort of tapered off in that it typically downloads the last approx 5-6 installs. So I stopped worrying about it at that point.
At the moment my best guess (i.e. have done 0 investigation on this, so take it with a grain of salt), is that it might download any releases in the last X days so that it has patches for them if a user is upgrading from a release that is a few versions old... but I really have no idea.

**Comment by MarshallOfSound** [comment]
This issue appears to have been resolved, Squirrel.Windows will only ever download a fixed quantity of past releases to generate deltas 👍
