### ISSUE TITLE
How long will the uninstallation last?

### ISSUE THREAD

**Issue by junjunruan** [electron/windows-installer#133]
I need to use node.js to execute some commands during uninstall the app:

```
const exec = require('child_process').exec;
exec('cat *.js bad_file | wc -l', (error, stdout, stderr) => {
  if (error) {
    console.error(`exec error: ${error}`);
    return;
  }
  console.log(`stdout: ${stdout}`);
  console.log(`stderr: ${stderr}`);
});
```

My questions are:
1. How long will the uninstallation last?
2. What if the exec() run longer than the uninstallation process? Will it be interrupted?

**Comment by MarshallOfSound** [comment]
The README indicates you have ~15 seconds to handle these squirrel events, if your command takes longer than that it will terminate your app
