### ISSUE TITLE
Remotereleases

### ISSUE THREAD

**Issue by matthewsuan** [electron/windows-installer#135]
If I provide the feed url `remoteReleases` during build, do I still invoke `autoUpdater.setFeedURL()` inside the app?

The documentation seems confusing and has no mention of this. 

Thanks!

**Comment by MarshallOfSound** [comment]
@matthewsuan Yes you still need to call `setFeedURL`

The `remoteRelease` property is specific to the installer build process and does not set any values for the installed application.
