### ISSUE TITLE
 set setupIcon attribute error 

### ISSUE THREAD

**Issue by ganxunzou** [electron/windows-installer#138]
![2016-09-24_170512](https://cloud.githubusercontent.com/assets/5092728/18807432/4b72ad88-8279-11e6-9b92-8e040e38f8eb.png)

**Comment by MarshallOfSound** [comment]
@ganxunzou Try making the `ico` path absolute instead of relative

**Comment by ganxunzou** [comment]
Thank you for your help!
After trying, I found that is not `setupIcon` attribute problem, but `iconUrl` problem. set `iconUrl` set HTTP mode is OK .

I have a suggestion : attribute increase example
