### ISSUE TITLE
export silently failing when using installer but not in release

### ISSUE THREAD

**Issue by barbalex** [electron/windows-installer#139]
In my app users can export data to excel .xlsx files thanks to [exceljs](https://github.com/guyonroche/exceljs).
I found out that in electron I need to run exceljs in a separate process for it to work.

Exporting this way works fine in dev mode and when running the .exe file in the release folder.
But fails silently when using the .exe file generated by the installer.
Silently means: No error occurs. If I leave chrome devtools open, no error is shown in the console.

I am using:
- windows 10
- node 6.5.0
- npm 3.10.3

package.json is: https://gist.github.com/barbalex/afa83bbb8e8b7bfd4f01606c0d837503
package.js is: https://gist.github.com/barbalex/64c586273491257b1351207706f6b011
Gruntfile.js is: https://gist.github.com/barbalex/003f1119ff229ea2bf14b65dd4ec08bb

These are the two functions running in separate processes when the export silently fails:
https://gist.github.com/barbalex/b6a5cffca04ace9aa8c54b368b9ba0ec
https://gist.github.com/barbalex/bf16a32924d50210d348e42f64c7c83f

Please tell me if I need to debug in a special (and unknown to me way) or raise this issue somewhere else. I am a bit at a loss on how to proceed.

To be honest it may well be that I am not using windows-installer correctly as I probably don't understand all the tools working together to produce the .exe.
Unrelated to this issue: Obviously I am doing _something_ wrong as the installer generates no start menu entry :-(

Also, working with multiple processes is new to me.

Help is much appreciated

**Comment by barbalex** [comment]
Update: 

I now found out that the error occurs on my clients windows 10 pc's when running the .exe file in the release folder. Could this possibly be caused by permissions or some form of "close down" on pc's inside a corporate network?

**Comment by MarshallOfSound** [comment]
This appears to be independent of Squirrel.Windows and caused by something machine specific on your client's network / PC.
