### ISSUE TITLE
Auto start after machine wide install

### ISSUE THREAD

**Issue by Arcath** [electron/windows-installer#142]
I have a small app that runs on login and sits in the system tray.

Using the msi generated here it runs the squirrel install tasks no problem but needs the user to log off and back on again before the app start properly.

Is there an option I can use to make squirrel start the app after it installs it from the machine wide installer? or something I can do in my install function that starts the app?

**Comment by damieng** [comment]
The msi isn't a machine-wide installer. It's a stub that installs the regular version automatically for all users as they log-in.

**Comment by Arcath** [comment]
yeah and when it installs it calls my app with `--squirrel-install` which works great, it puts itself in auto start for that user like it is uspposed to BUT it doesn't start that time. The normal installer starts the app after it installs where as the machine wide one doesnt.

To use something like a child process to run the app I would need to be able to tell if this was the install shim or the normal installer. Is there anything passed differently when the machine wide installer runs the install?

**Comment by damieng** [comment]
The actual building and execution of the msi (and regular installer) is delegated to Squirrel.Windows. I don't think there is anything electron/windows-installer can do to facilitate that.

**Comment by MarshallOfSound** [comment]
If you are still interested in this feature you should raise a request over on Squirrel.Windows.  Please ensure that no such issue already exists 😄
