### ISSUE TITLE
Create shortcut when first run install

### ISSUE THREAD

**Issue by dungvt** [electron/windows-installer#145]
Hi all,
I have an issue about shortcut of my application when the first install from win-installer package.
It not create shortcut and i can't find an option to config shortcut on installer.js.
My config code here:

```
function getInstallerConfig() {
   const outPath = path.join(__dirname, '../../../deployments/release/')
   return Promise.resolve({
     appDirectory: path.join(__dirname, '../../../deployments/PixelzEditorClient-win32-x64'),
     outputDirectory: path.join(outPath, 'windows-installer'),
     exe: 'PixelzEditorClient.exe',
     authors: 'Pixelz Inc.',
     description: `This is application for Pixelz's Photo Editor`
   })
}
```

Thanks for reading.

**Comment by MarshallOfSound** [comment]
The information you are looking for is in the README

https://github.com/electron/windows-installer#handling-squirrel-events

> The electron-squirrel-startup module will handle the most common events for you, such as managing desktop shortcuts. Just add the following to the top of your main.js and you're good to go:
