### ISSUE TITLE
Uninstall not invoked 

### ISSUE THREAD

**Issue by dventurino** [electron/windows-installer#147]
While the _--squirrel-firstrun_ event is invoked and my program runs all the commands it has to, the _--squirrel-uninstall_ event does not seem to be fired (even though the shortcut created by default is removed).

I don't even see the uninstall event in my logs...does the uninstall in Windows "Programs and features" invoke the application with the --squirrel-uninstall flag ?

**Comment by MarshallOfSound** [comment]
Hey 👋 

This issue is being closed as it is stale.  This normally means that the issue has been fixed in newer versions or this issue or no longer impacting you.  If this is not the case please feel free to comment with and @ mention me and we can revisit this.
