### ISSUE TITLE
iconUrl not picking up

### ISSUE THREAD

**Issue by nidhir-systango** [electron/windows-installer#148]
i see electron default icon displayed in Control Panel > Programs and Features even adter adding iconUrl attribute:

   #!/usr/bin/env node

  const createWindowsInstaller = require('electron-winstaller').createWindowsInstaller
  const path = require('path')
  const rimraf = require('rimraf')

  deleteOutputFolder()
    .then(getInstallerConfig)
    .then(createWindowsInstaller)
  .  catch((error) => {
    console.error(error.message || error)
    process.exit(1)
    })

  function getInstallerConfig () {
    const rootPath = path.join(__dirname, '..')
    const outPath = path.join(rootPath, 'dist')

  return Promise.resolve({
    appDirectory: path.join(outPath, 'win-unpacked'),
    outputDirectory: path.join(outPath, 'windows-installer'),
    iconUrl: 'https://onepgr.com/images/service/codesktop_icon.ico',
    loadingGif: path.join(rootPath, 'app', 'assets', 'img', 'loading.gif'),
    noMsi: true,
    setupExe: 'CoDesktop.exe',
    setupIcon: path.join(rootPath, 'app', 'assets', 'img', 'CoDesktopLogoFinal_Icon.ico'),
    skipUpdateIcon: true
    })
  }

  function deleteOutputFolder () {
     return new Promise((resolve, reject) => {
      rimraf(path.join(__dirname, '..', 'out', 'windows-installer'), (error) => {
       error ? reject(error) : resolve()
     })
   })
  }

i am making a windows application on windows machine.
please help me out of this, Thanks in advance.

**Comment by Sunyang730** [comment]
What version of Windows are you working on?

**Comment by MarshallOfSound** [comment]
Windows can sometimes cache these icons so if you have installed it once you need to figure out how to clear that cache I believe.

**Comment by nidhir-systango** [comment]
i just restart my system and it works.
Thnaks for your help.

**Comment by davydany** [comment]
This needs to be documented. I wasted 2 days before finding this issue, and a simple restart fixed `iconURL` not updating.

**Comment by LeGmask** [comment]
I'm fully agree with @davydany i'm working on this since 3 days but can't work before restart ...
