### ISSUE TITLE
Possible to use a local file for iconUrl instead of an actual Url?

### ISSUE THREAD

**Issue by Sunyang730** [electron/windows-installer#151]
Hi,

I can get it working on my build system, but when installed by other users the add & remove program does not show the icon. I believe this is due to the icon does not pack with the installer?

I see that I can add <file> with the nuspectemplate. Possible to add the icon as a content file and use that instead?

**Comment by Thomas101** [comment]
I was wondering the same thing -- just came up against the same issue

**Comment by develar** [comment]
@Thomas101 [electron-builder](http://github.com/electron-userland/electron-builder) supports NSIS to produce windows installer and no such strange nupkg requirements.

**Comment by cnsdato** [comment]
This is still an issue. You can work around this by using an file:// URL and point to the .ico file.
But there is no chance to use this relative to the project, so the file:// URL must be absolute and this is a no go when using the project on different development environements.

**Comment by MarshallOfSound** [comment]
This is a requirement upstream (nupkg) and `electron/windows-installer` cannot change this requirement.  Simply statically hosting your icon in a GH release or on S3 would work and be quite easy 👍

**Comment by mix3d** [comment]
Static hosting of Icon does not work when installing offline or in private networks.

**Comment by ThomasStubbe** [comment]
Won't this work? 

`iconUrl: "file://" + __dirname  + "/resources/icon.ico",`

**Comment by mix3d** [comment]
No it does not. You get build errors.

**Comment by mor-o** [comment]
can we reopen this? this is still an issue on private networks with no access to the internet

**Comment by Volburt7** [comment]
> Won't this work?
> 
> `iconUrl: "file://" + __dirname + "/resources/icon.ico",`

Well this worked for me to a certain extend. This made that the icon inside "Programs and Features" is the correct one.

Desktop Shortcut and App Icon seem to continue not to be shown correct, but apparently it is a caching issue with windows since I somehow managed to fix it once by deleting this file and restarting `C:\Users\%username%\AppData\Local\IconCache.db`.
However I was not able to reproduce it again..

**Comment by duonghn** [comment]
@Volburt7 which Windows are using to build the setup? The `file://` worked by me with Win11 but not with Windows 10. Thanks!
