### ISSUE TITLE
Is it possible to build the 32 bit installer on a 64 bit system?

### ISSUE THREAD

**Issue by cruzerld** [electron/windows-installer#154]
All my Windows OSes are 64 bit, but I need a 32 bit installer. Can this package build a version that isn't the system arch?

The electron-packager bundle works correctly, but when I try to install I get a '%1 is not a valid Win32 application' pointing to a random .node file in AppData\Local\Temp\XXXX.tmp.node where XXXX is a random set of chars.

The 64 bit installer works fine. Can anyone here help me out?

**Comment by MarshallOfSound** [comment]
Looks like you need to rebuild your native modules with `electron-rebuild` or something similar.

The .node file in the temp directory is one of your native modules extracted from your ASAR.

**Comment by paulcbetts** [comment]
Yep, this isn't an installer bug, this is your app being not 32-bit. To answer your question though, it's definitely possible, @MarshallOfSound is onto the right idea here. The Squirrel installer is always a 32-bit executable, even on 64-bit platforms

**Comment by jadhavrani123** [comment]
I want to create two different exe for 32bit & 64bit exe?
