### ISSUE TITLE
Virus warning during install

### ISSUE THREAD

**Issue by Bruce17** [electron/windows-installer#156]
I installed your package on my local Win7 x64 machine with the command `npm i electron-forge --save-dev`. Suddenly my virus scanner alerted:

![image](https://cloud.githubusercontent.com/assets/5036995/21857710/b3fdabb6-d826-11e6-82a9-0a8eb9099688.png)

So I did some research:
* After the installation process I checked the folder `node_modules/.staging`, but it didn't exist anymore.
* I checked your project via [snyk.io](https://snyk.io) 2 issues. I created a pull request https://github.com/electron/windows-installer/pull/155. I'm not sure if this fixed this issue/removes the malicious file.

At the moment, I don't fell safe using your module.

**Comment by paulcbetts** [comment]
Some crappy virus scanners pick up Squirrel.Windows's Setup.exe as a virus because it installs software.  You can read the full source to this executable over at https://github.com/Squirrel/Squirrel.Windows/tree/master/src/Setup
