### ISSUE TITLE
Ballooning File size

### ISSUE THREAD

**Issue by ianrtracey** [electron/windows-installer#158]
This might be user error but the size of my windows installer and nuget file are drastically increasing despite no core code changes.

On the initial generation of the installer I was seeing a 89Mb Setup.exe and  and 89Mb *.full.npkg. After the second and all subsequent installer generations I am seeing a 273Mb Setup.exe and a 274Mb *.full.npkg file.

This is becoming a problem because it's making the distribution of the app difficult due to long upload and download times. I suspect this has something to do with how changes are being tracked between versions? I have tried searching for similar problems with install and nuget file sizes but have turned up empty handed.

Anyone have any ideas?

**Comment by MarshallOfSound** [comment]
Sounds like you're including the last installer in the new installer.  Ensure your are ignoring your output directory when packaging / making the installer

**Comment by ianrtracey** [comment]
@MarshallOfSound: I thought about that. I am removing the contents in my build/ directory each time in order to avoid having those problems.

**Comment by MarshallOfSound** [comment]
@ianrtracey It's almost certainly not quite deleting the right folder then.

Quick maths shows that

* 89 (packaged app)
* 89 (old installer)
* 89 (old nupkg)
* ~7 (delta nupkg and loose files)

adds up to your new total, you probably are still adding your dist files to your installer 👍 

You can verify this by extracting the `nupkg` file and inspecting the content

**Comment by ianrtracey** [comment]
@MarshallOfSound: Thanks for your help! I followed an example online for using this module that had both appDirectory and outputDirectory as 'build/'. That turned out to give me issues and once I had the installer output to 'installers/' I had no more issues.
