### ISSUE TITLE
Install other installer and run it before continuing my install

### ISSUE THREAD

**Issue by dotmaik1** [electron/windows-installer#160]
My electron app will need "C++ 2010 Redistributable Package" installed on the target machine to work, I want to know if there is a way to include it within my windows-installer's .exe or if there is another way, like to trigger a download and install of that dependency

Thanks

**Comment by MarshallOfSound** [comment]
GitHub issues are for feature requests and bug reports, questions about using Electron or code assistance requests should be directed to the [community](https://github.com/electron/electron#community) or to the [Slack Channel](http://atom-slack.herokuapp.com/).
