### ISSUE TITLE
Installation Directory

### ISSUE THREAD

**Issue by Qilly** [electron/windows-installer#161]
I've got a Win64 electron-based app and I'm now trying to create an installer for it. Running the example program creates `C:\Program Files (x86)\<AppName> Installer` which is unfortunate. I'd prefer to be able to change this to `C:\Program Files\<Company>\<AppName>` - is there any scope for doing this?

**Comment by MarshallOfSound** [comment]
This has been requested before and goes against some of the fundamental principles of Squirrel.Windows.

**Comment by Qilly** [comment]
Well that's unhelpful. Why does it go against the fundamental principles of Squirrel.Windows? As I understand it, 32-bit programs are supposed to go into "Program Files (x86)" and 64-bit programs go into "Program Files". This means my program is going into the wrong place, which is a big issue for some environments.

I'm happy to hear the reasons why you're unwilling/unable to make this change but right now your response is unhelpful.

**Comment by MarshallOfSound** [comment]
@Qilly I'm sorry you feel my response didn't explain this well enough.

Check out the [What do we want](https://github.com/Squirrel/Squirrel.Windows#what-do-we-want) section of the `Squirrel.Windows` README.  In particular the line referenced below:

> Installing is Wizard-Free™, with no UAC dialogs, does not require reboot, and is .NET Framework friendly.

The key part here is `"no UAC dialogs"`, installing to anything in `C:\Program Files` or `C:\Program Files (x86)` requires UAC and is therefore not possible to achieve these goals.  As for your statement:

> This means my program is going into the wrong place

There is no set place for programs to go on windows, you can put them wherever you want.  There are conventions and one of those is to put them in the `userData` directory for an individual user.

**Comment by Qilly** [comment]
Thanks for the more full explanation. I'm now confused and will go back to carefully look at whether things have changed in the past year. The problem was that originally the installer actually did go to C:\Program Files (x86) and therefore did require UAC anyway. Perhaps I made a mistake at that time or perhaps that was changed.

It certainly makes sense for programs that update themselves not to constantly require UAC for this to occur smoothly and that's definitely what Squirrel does.

I posted this in windows-installer, thinking that there was a difference between Squirrel and the "windows-installer" project. Or did one replace the other?

Anyway, thanks again for the clarification.

**Comment by MarshallOfSound** [comment]
> Perhaps I made a mistake at that time or perhaps that was changed.

`electron-winstaller` has always used Squirrel.Windows and never installed to "Program Files", perhaps you were using a different tool? 🤔

**Comment by DrakeXiang** [comment]
> > Perhaps I made a mistake at that time or perhaps that was changed.
> 
> `electron-winstaller` has always used Squirrel.Windows and never installed to "Program Files", perhaps you were using a different tool? 🤔

I just encountered this problem, does building a `msi` distribution enable clients to select installation path?
