### ISSUE TITLE
Verbose Building Messages

### ISSUE THREAD

**Issue by PythonDevOp** [electron/windows-installer#164]
Is there any way to add logging or verbosity when the installer is being created? The promise either returns 'it worked' or 'no dice', and doesn't give you any idea of what happens in between start and end. This is what I am referring to: `resultPromise.then(() => console.log("It worked!"), (e) => console.log(`No dice: ${e.message}`));`

Is there logging built in, no just those options?

**Comment by ianrtracey** [comment]
+1

**Comment by jonmanzo** [comment]
? https://github.com/electron/windows-installer#debugging-this-package

**Comment by PythonDevOp** [comment]
Unless I am missing something (or doing it wrong), setting DEBUG=electron-windows-installer:main doesn't work. 

I am using an npm script to run the file containing the installer options. Do I need to specify that file or script as the target of the debug?
