### ISSUE TITLE
\node_modules\electron-winstaller\vendor\Update.exe disappears after each build

### ISSUE THREAD

**Issue by DaveRicho** [electron/windows-installer#165]
Hi Guys, 

Please accept my apologies in advance if this has already been addressed (I have been looking) or if you can see I am making some obvious mistakes or omissions in this issue posting (I'm still very much a newbie).

I'm on windows 8.1 running node version 7.7.3 (maybe someone will tell me that is the problem right there......).

Each time I run my js file named "winstaller.js" (using "node winstaller.js")  I get the following:

No dice: ENOENT: no such file or directory, lstat 'C:\myproject\node_modules\electron-winstaller\vendor\Update.exe'

I have been physically checking the folder 'C:\myproject\node_modules\electron-winstaller\vendor\' and to my surprise, 'update.exe' does seem to get deleted each time.

Here is what my "winstaller.js" file looks like in case that helps.

`var electronInstaller = require('electron-winstaller');

var resultPromise = electronInstaller.createWindowsInstaller({
    appDirectory: './releases/myprojectelectron-win32-ia32',
    outputDirectory: './releases/installer32',
    authors: 'Me',
    loadingGif: './src/assets/images/spinning.gif',
    setupExe: 'myprojectElectronSetup.exe',
    noMsi: true,
    description: 'myproject electron',
    exe: 'myprojectelectron.exe'
  });
 
resultPromise.then(() => console.log("It worked!"), (e) => console.log(`No dice: ${e.message}`));`

To get the 'C:\myproject\node_modules\electron-winstaller\vendor\Update.exe' file back, I need to reinstall using npm install --save-dev electron-winstaller. 

Thanks in advance to anyone who has any ideas.

**Comment by DaveRicho** [comment]
I think I may have found the problem - it looks like my anti virus software is doing the deleting.

I guess this is why the docs say "Sign your installer or else bad things will happen". 

Sorry for wasting anyone's (and possibly everyone's) time.

**Comment by DaveRicho** [comment]
The unsigned files that is causing the issue is node_modules\electron-winstaller\vendor\Update.exe.

Is anyone else having this problem? (Anti virus thinks Update.exe is malicious)

**Comment by MarshallOfSound** [comment]
This is a false positive, you should add either the hash of `Update.exe` or the path "node_modules/electron-installer/*` to your anti-virus whitelist
