### ISSUE TITLE
Successful build, but no response after clicking setup.exe

### ISSUE THREAD

**Issue by LazeBear** [electron/windows-installer#166]
when I first clicked Setup.exe there was a little green window popped up and quickly disappeared, other than that, no responses. 
I've tried run as Admin, no response.
I've tried run the Setup.msi, no response.
Anyone have this problem before?

**Comment by LazeBear** [comment]
![untitled](https://cloud.githubusercontent.com/assets/19187875/24482497/f7b2e5b0-1534-11e7-9148-f82bc6943d36.png)
it disappeared afterwards

**Comment by brenca** [comment]
This is the default installer gif being displayed while installing, you can override it in the options.
