### ISSUE TITLE
README needs update for "Handling Squirrel Events" with babel/ES6

### ISSUE THREAD

**Issue by dixon13** [electron/windows-installer#181]
This was an issue for me and after awhile of googling figured it out. The README needs an update for development environments using babel or ES6. Reference [this](https://github.com/mongodb-js/electron-squirrel-startup#usage) for information that should be added to this repo's README.

**Comment by MarshallOfSound** [comment]
The existing code works fine even in a `babel` or ES6 environment if someone wants to do some docs improvements and PR some new stuff into the README by all means.  But for now the docs are accurate 👍
