### ISSUE TITLE
How to remove the previous versions after auto update?

### ISSUE THREAD

**Issue by weiluenju** [electron/windows-installer#183]
Auto update work fine for my app, but when I going to the AppData folder. I see many folders which start with "app-".

I try to remove those folders by code after update, but always say the files "app.asar" and "electron.asar" are using(lock).

How can I remove the previous versions after auto update? or I miss something need to do after the update? Thank you very much.

![electron](https://user-images.githubusercontent.com/10330207/27315218-f500ab7a-55aa-11e7-8c31-59f60a5dcacc.png)

**Comment by MarshallOfSound** [comment]
Only 1 version should remove after each update, in some scenarios 3 versions can exist simultaneously.  In no case should more than 3 exist.

Squirrel.Windows will clean old versions up for you 👍
