### ISSUE TITLE
Cannot find module 'electron-squirrel-startup'

### ISSUE THREAD

**Issue by sumanta-ghosh** [electron/windows-installer#193]
First I generate exe using electron-packager then use  node build.js give me the single installer file every things is okay but wehn I try to create some shorcut in desktop and start menu then at the installation time I got this issue.

![image](https://user-images.githubusercontent.com/29307749/28369699-036601ac-6cb6-11e7-9ad4-0eae8bb5af2b.png)

**package.json**

```json
{
  "name": "HelloWorld",
  "description": "Skg Electron",
  "version": "0.1.0",
  "app-version": "1.0",
  "private": true,
  "author": "Sumanta Kr Ghosh",
  "license": "ISC",
  "main": "main.js",
  "dependencies": {
    "pretty-bytes": "^2.0.1"
  },
  "devDependencies": {
    "electron": "^1.7.4",
    "electron-installer-windows": "^0.2.0",
    "electron-packager": "^8.7.2",
    "electron-squirrel-startup": "^1.0.0",
    "electron-winstaller": "^2.6.3"
  },
  "scripts": {
    "start": "electron main.js",
    "build": "electron-packager . --overwrite --asar=true --platform=win32 --arch=ia32 --iconUrl=images/green.ico --prune=true --out=Desktop/electron-workspace/ --version-string.CompanyName=\"Test\" --version-string.FileDescription=\"TestDescription\" --version-string.ProductName=\"Test\"",
   }
}

```

**build.js**

``` javascript
const createWindowsInstaller = require('electron-winstaller').createWindowsInstaller
const path = require('path')

getInstallerConfig()
        .then(createWindowsInstaller)
        .catch((error) => {
            console.error(error.message || error)
            process.exit(1)
        })

function getInstallerConfig() {
    console.log('creating windows installer');
    const rootPath = path.join('./');
    console.log(rootPath);
    const outPath = path.join(rootPath, 'release-builds');

    return Promise.resolve({
        appDirectory: './Infoway-CRM-win32-ia32',
        authors: 'Sumanta Kr Ghosh',
        owners:'Infoway',
        noMsi: true,
        outputDirectory: './dist',
        exe: 'Infoway-CRM.exe',
        setupExe: 'crm.exe',
        setupIcon: 'yellow.ico',
        iconUrl:'http://localhost/infoway-crm/installer.ico',
        loadingGif:'installing.gif'
    })
}
```

**main.js**

```javascript
const electron = require('electron');
const {app, Tray, BrowserWindow, ipc, ipcMain} = electron;
if (require('electron-squirrel-startup')) return;
if (handleSquirrelEvent()) {
    // squirrel event handled and app will exit in 1000ms, so don't do anything else
    return;
}

//Other code

// In this file you can include the rest of your app's specific main process
// code. You can also put them in separate files and require them here.
function handleSquirrelEvent() {
  if (process.argv.length === 1) {
    return false;
  }

  const ChildProcess = require('child_process');
  const path = require('path');

  const appFolder = path.resolve(process.execPath, '..');
  const rootAtomFolder = path.resolve(appFolder, '..');
  const updateDotExe = path.resolve(path.join(rootAtomFolder, 'Update.exe'));
  const exeName = path.basename(process.execPath);

  const spawn = function(command, args) {
    let spawnedProcess, error;

    try {
      spawnedProcess = ChildProcess.spawn(command, args, {detached: true});
    } catch (error) {}

    return spawnedProcess;
  };

  const spawnUpdate = function(args) {
    return spawn(updateDotExe, args);
  };

  const squirrelEvent = process.argv[1];
  switch (squirrelEvent) {
    case '--squirrel-install':
    case '--squirrel-updated':
      // Optionally do things such as:
      // - Add your .exe to the PATH
      // - Write to the registry for things like file associations and
      //   explorer context menus

      // Install desktop and start menu shortcuts
      spawnUpdate(['--createShortcut', exeName]);

      setTimeout(electron.quit, 1000);
      return true;

    case '--squirrel-uninstall':
      // Undo anything you did in the --squirrel-install and
      // --squirrel-updated handlers

      // Remove desktop and start menu shortcuts
      spawnUpdate(['--removeShortcut', exeName]);

      setTimeout(electron.quit, 1000);
      return true;

    case '--squirrel-obsolete':
      // This is called on the outgoing version of your app before
      // we update to the new version - it's the opposite of
      // --squirrel-updated

      app.quit();
      return true;
  }
};
```

**Comment by MarshallOfSound** [comment]
You currently have electron-squirrel-startup as a devDependency so it will be removed during the build steps of most Electron packaging tools. Move it to the dependencies section :+1:

**Comment by clark-97** [comment]
> You currently have electron-squirrel-startup as a devDependency so it will be removed during the build steps of most Electron packaging tools. Move it to the dependencies section 👍

electron-squirrel-startup is in the dependencies section now, but I got same error @MarshallOfSound

**Comment by AndreiIl** [comment]
> > You currently have electron-squirrel-startup as a devDependency so it will be removed during the build steps of most Electron packaging tools. Move it to the dependencies section 👍
> 
> electron-squirrel-startup is in the dependencies section now, but I got same error @MarshallOfSound

In my case, it didn't work either but the cause was the fact that I was developing the electron app as part of a monorepo (Lerna) where the dependency management was being handled by Yarn Workspaces. What yarn is doing is [hoisting](https://classic.yarnpkg.com/blog/2018/02/15/nohoist/) the npm dependencies of all packages in the root level ( outside of the packages ) directory node_modules to avoid redundancy and creates symlinks so that when referencing them in code, the compiler knows where to look. The problem is that **not all crawlers traverse [symlinks](https://github.com/facebook/metro/issues/1)**, and that, apparently, includes what Windows Installer uses. 

To fix this, I had to add the nohoist config in my root package.json worspaces configuration to ... not hoist my electron's dependencies so that they are left inside the specific the node_modules:

`
"workspaces": {
    "packages": ["packages/*"],
    "nohoist": [
      "my-electron-app/**"
    ]
  }
`

Hope this helps!

**Comment by LZQCN** [comment]
> > > You currently have electron-squirrel-startup as a devDependency so it will be removed during the build steps of most Electron packaging tools. Move it to the dependencies section 👍
> > 
> > 
> > electron-squirrel-startup is in the dependencies section now, but I got same error @MarshallOfSound
> 
> In my case, it didn't work either but the cause was the fact that I was developing the electron app as part of a monorepo (Lerna) where the dependency management was being handled by Yarn Workspaces. What yarn is doing is [hoisting](https://classic.yarnpkg.com/blog/2018/02/15/nohoist/) the npm dependencies of all packages in the root level ( outside of the packages ) directory node_modules to avoid redundancy and creates symlinks so that when referencing them in code, the compiler knows where to look. The problem is that **not all crawlers traverse [symlinks](https://github.com/facebook/metro/issues/1)**, and that, apparently, includes what Windows Installer uses.
> 
> To fix this, I had to add the nohoist config in my root package.json worspaces configuration to ... not hoist my electron's dependencies so that they are left inside the specific node_modules:
> 
> `"workspaces": { "packages": ["packages/*"], "nohoist": [ "my-electron-app/**" ] }`
> 
> Hope this helps!

I am using npm workspaces and have encountered the same problem.

**Comment by movahhedi** [comment]
I use ESM + Typescript, so for me, it should be written like this:
```ts
// main.ts
import Squirrel from "electron-squirrel-startup";

// Handle creating/removing shortcuts on Windows when installing/uninstalling.
// if (require("electron-squirrel-startup")) {
if (Squirrel) {
	app.quit();
}
```

**Comment by Super-Kenil** [comment]
> I use ESM + Typescript, so for me, it should be written like this:
> 
> // main.ts
> import Squirrel from "electron-squirrel-startup";
> 
> // Handle creating/removing shortcuts on Windows when installing/uninstalling.
> // if (require("electron-squirrel-startup")) {
> if (Squirrel) {
> 	app.quit();
> }

This helped, thanks
