### ISSUE TITLE
AVG detect it is a virus

### ISSUE THREAD

**Issue by sumanta-ghosh** [electron/windows-installer#195]
Antivirus(AVG) detect the setup.exe as a virus

![image](https://user-images.githubusercontent.com/2699051/28615025-5f5bc302-7215-11e7-9a2f-be0d3921e56e.png)

![image](https://user-images.githubusercontent.com/2699051/28615069-7d0e8a38-7215-11e7-9498-13bb3c14268a.png)

**Comment by MarshallOfSound** [comment]
It's a false positive and you should report it as such.  AV programs get false positives like this all the time

**Comment by sumanta-ghosh** [comment]
@MarshallOfSound but week ago it was working fine no issue was there. Today after reinstalling all packages I got this issue.

**Comment by MarshallOfSound** [comment]
@sumanta-ghosh Sure, AV's change their database and detection algorithms all the time, sometimes unfortunate false positives like this occur.
