### ISSUE TITLE
Upgrade to Squirrel 1.7.8

### ISSUE THREAD

**Issue by jonoomph** [electron/windows-installer#205]
There is a new version of Squirrel (released on Aug 8), that addresses issues with "delta" installers. It seems that Squirrel binaries are included in this project (sorry if I am misunderstanding)... thus the request to update them to the latest release: https://github.com/Squirrel/Squirrel.Windows/releases/tag/1.7.8

Delta bug report that is supposed to be addressed in Squirrel 1.7.8:
https://github.com/Squirrel/Squirrel.Windows/issues/1104

Thanks a bunch!

**Comment by jonoomph** [comment]
Looks like there is a pull request to upgrade Squirrel to 1.7.8: https://github.com/electron/windows-installer/pull/199

**Comment by devtobo** [comment]
Is windows-installer using this version of Squirrel 1.7.8, because the delta are not working for my electron application. So the user is downloading the delta & then the full package. Not good...

**Comment by baconbrad** [comment]
Any update on this?

**Comment by damieng** [comment]
Updated to 1.7.9 in #224
