### ISSUE TITLE
loadingGif - slow and image appears scaled down?

### ISSUE THREAD

**Issue by JohnRSim** [electron/windows-installer#207]
![installing-animation-small](https://user-images.githubusercontent.com/364208/30440625-075f1a88-996f-11e7-9bfb-03798b52fe77.gif)

I'm trying to set this as a loading gif but when I install the gif appears half the size and runs slower than running natively?

I didn't see any options to set the gif size or ways to improve performance.
Atoms installer gif runs smoothly..
https://i.github-camo.com/2c08678c355ef710338f4abf170cc999501b4093/68747470733a2f2f662e636c6f75642e6769746875622e636f6d2f6173736574732f36393136392f323239303235302f63333564383637612d613031372d313165332d383662652d6364376335626633666639622e676966

Any thoughts -

**Comment by debelop13** [comment]
Because is using last version (1.7.8) of Squirrel.Windows: https://github.com/Squirrel/Squirrel.Windows/issues/1124

I have same problem and also is rendering without transparency. 
Exists way to use previos version?

**Comment by asimionese** [comment]
Try to put a 2x larger gif

**Comment by Thieum** [comment]
@shiftkey this should be fixed by #1233 like #1124 , this can be closed.
