### ISSUE TITLE
how to create a msi as exe which is generated is launching everytime as a new app

### ISSUE THREAD

**Issue by vamshisana** [electron/windows-installer#211]
Hi 
I have created an exe with steps given in https://github.com/electron/windows-installer, My Issue is whenever i launch the exe close it and open it again, It launches as a new instance and the all the data of the last instance gets lost.

**Comment by MarshallOfSound** [comment]
> It launches as a new instance and the all the data of the last instance gets lost.

There are two ways to interpret what you are doing so I'll respond to both 😄 

1. You are launching the `Setup.exe` generated by this tool multiple times

This is how installers are expected to work, you are running the installer multiple times which is reinstalling the application each time

2. You are launching the installed `MyApp.exe` multiple times

This is how applications work, OS's (in this case Windows) don't magically persist the state of your application and recreate it for you next time your app is launched.  If you want to persist data between launches you will need to do that yourself.

**Comment by vamshisana** [comment]
Hi Samuel,
Cant we generate an msi using electron so that it  won't launch as new
instance every time we launch the app as myapp.exe is always launching as
an new instance

Or

Can we use this exe using any of the tools to generate a msi so that it
wont launch as new instance
