### ISSUE TITLE
Bug: setupIcon configuration caused error `Unable to load file`

### ISSUE THREAD

**Issue by matsnow** [electron/windows-installer#233]
I executed this script on Windows10. (add `setupIcon`)
```js
const electronInstaller = require('electron-winstaller');
electronInstaller.createWindowsInstaller({
    appDirectory: '/tmp/build/my-app-64',
    outputDirectory: '/tmp/build/installer64',
    authors: 'My App Inc.',
    setupIcon: 'test.ico',
    exe: 'myapp.exe'
})
.then(() => console.log('It worked!'))
.catch((e) => console.log(`No dice: ${e.message}`));
```

Then caused `Unable to load file` error.
```sh
No dice: Failed with exit code: 1
Output:
Fatal error: Unable to load file
```

Of course, file paths are no problem, and changed them to absolute, but not working.

Result of investigation, it seem to was failed to execute `rcedit.exe`.
`rcedit.exe` calls `LoadLibraryEx()`, but it returns NULL and error code is 0x20 (ERROR_SHARING_VIOLATION).
In addition, I executed `rcedit.exe` on CLI is successful.

I guess that `fsUtil.copy` doesn't release `appDirectory/Update.exe` (https://github.com/electron/windows-installer/blob/master/src/index.js#L43) .
Thus `LoadLibraryEx()` causes ERROR_SHARING_VIOLATION.

On trial I replaced `fsUtil.copy` to `require(‘fs’).copyFileSync`, it was fixed.
For now I add `skipUpdateIcon ` and execute `rcedit.exe` on external script. But, more better way is update `fs-extra` to v2.1.x. 
If there is more better solution, please tell me.

**Comment by TStod** [comment]
+1 having the same issue

**Comment by matsnow** [comment]
https://github.com/electron/windows-installer/releases/tag/v2.6.4

**Comment by ozankonur** [comment]
I am still getting this error, `setupIcon: path.join('C:\\CTL\\icon.ico'),`
