### ISSUE TITLE
StubExecutable.exe considered as a virus by BitDefender

### ISSUE THREAD

**Issue by phbernard** [electron/windows-installer#245]
On my machine, BitDefender considers [StubExecutable.exe](https://github.com/electron/windows-installer/blob/master/vendor/StubExecutable.exe) as a virus and deletes it.

To reproduce the issue:
- Install BitDefender AntiVirus Plus 2018 (although I have no reasons to think that another version will give other results)
- Download https://github.com/electron/windows-installer/blob/master/vendor/StubExecutable.exe (commit bad4bdf  on 17 Jan). At this point, BitDefender should display a notification and prevent the file from being stored.
- If the previous step was not conclusive, run BitDefender manually on the downloaded executable.

**Comment by MarshallOfSound** [comment]
This is a false positive, please ensure your application is signed with a valid and trusted code signing cert.

**Comment by wooandoo** [comment]
I have the same issue.
Why do you think is a false positive?
Because, BitDefender detected the signature of the virus "Gen:Variant.Zusy.286249" in the file "StubExecutable.exe"!

**Comment by phbernard** [comment]
FYI I have posted the file as a false positive to Bitdefender (https://www.bitdefender.com/submit/)

**Comment by phbernard** [comment]
I've re-run BitDefender: there is no more error, whereas StubExecutable.exe was not updated since then. It must mean the change comes from BitDefender, which in turn implies that it was a false positive from the beginning.

@wooandoo : it would be interesting to double check on your side. After all, this issue was quite alarming.

**Comment by wooandoo** [comment]
@phbernard I checked the file again, and I have no more errors ;-)
