### ISSUE TITLE
StubExecutable.exe reports as malware

### ISSUE THREAD

**Issue by sbhobbs** [electron/windows-installer#246]
Hi all!

vendor\StubExecutable.exe reports as malware of type "Variant.Zusy" using Ivanti antivirus (I think this is BitDefender on the backend).

I get this on pulls of v2.5.0 and latest (v2.6.4).

I'm assuming a false positive?

**Comment by MarshallOfSound** [comment]
> I'm assuming a false positive?

👍 Yup, false positive
