### ISSUE TITLE
Supported .gif files

### ISSUE THREAD

**Issue by rahulbm** [electron/windows-installer#254]
I have replaced file at `electron_app\node_modules\electron-winstaller\resources`  with different gif file. After doing this my app is not getting installed on some Windows 10 system. 
It gives below error (logs from Event Viewer)

- <Event xmlns="http://schemas.microsoft.com/win/2004/08/events/event">
- <System>
  <Provider Name=".NET Runtime" /> 
  <EventID Qualifiers="0">1026</EventID> 
  <Level>2</Level> 
  <Task>0</Task> 
  <Keywords>0x80000000000000</Keywords> 
  <TimeCreated SystemTime="2018-07-04T11:19:10.000000000Z" /> 
  <EventRecordID>537359</EventRecordID> 
  <Channel>Application</Channel> 
  <Computer>BONTALABHARATH.HEALTHEC.COM</Computer> 
  <Security /> 
  </System>
- <EventData>
  <Data>Application: Update.exe Framework Version: v4.0.30319 Description: The process was terminated due to an unhandled exception. Exception Info: System.OutOfMemoryException Stack: at System.Windows.Media.Imaging.WriteableBitmap.InitFromBitmapSource(System.Windows.Media.Imaging.BitmapSource) at System.Windows.Media.Imaging.WriteableBitmap.CopyCommon(System.Windows.Media.Imaging.WriteableBitmap) at System.Windows.Media.Imaging.WriteableBitmap.CloneCurrentValueCore(System.Windows.Freezable) at System.Windows.Freezable.CloneCoreCommon(System.Windows.Freezable, Boolean, Boolean) at System.Windows.Freezable.CloneCurrentValueCore(System.Windows.Freezable) at System.Windows.Freezable.CloneCurrentValue() at System.Windows.Media.Animation.ObjectKeyFrameCollection.CloneCurrentValueCore(System.Windows.Freezable) at System.Windows.Freezable.CloneCurrentValue() at System.Windows.Media.Animation.ObjectAnimationUsingKeyFrames.CopyCommon(System.Windows.Media.Animation.ObjectAnimationUsingKeyFrames, Boolean) at System.Windows.Media.Animation.ObjectAnimationUsingKeyFrames.GetCurrentValueAsFrozenCore(System.Windows.Freezable) at System.Windows.Freezable.GetCurrentValueAsFrozen() at System.Windows.Media.Animation.Clock..ctor(System.Windows.Media.Animation.Timeline) at System.Windows.Media.Animation.AnimationTimeline.AllocateClock() at System.Windows.Media.Animation.Clock.AllocateClock(System.Windows.Media.Animation.Timeline, Boolean) at System.Windows.Media.Animation.Clock.BuildClockTreeFromTimeline(System.Windows.Media.Animation.Timeline, Boolean) at WpfAnimatedGif.ImageAnimationController..ctor(System.Windows.Controls.Image, System.Windows.Media.Animation.ObjectAnimationUsingKeyFrames, Boolean) at WpfAnimatedGif.ImageBehavior.InitAnimationOrImage(System.Windows.Controls.Image) at WpfAnimatedGif.ImageBehavior.ImageControlLoaded(System.Object, System.Windows.RoutedEventArgs) at System.Windows.RoutedEventHandlerInfo.InvokeHandler(System.Object, System.Windows.RoutedEventArgs) at System.Windows.EventRoute.InvokeHandlersImpl(System.Object, System.Windows.RoutedEventArgs, Boolean) at System.Windows.UIElement.RaiseEventImpl(System.Windows.DependencyObject, System.Windows.RoutedEventArgs) at System.Windows.UIElement.RaiseEvent(System.Windows.RoutedEventArgs) at System.Windows.BroadcastEventHelper.BroadcastEvent(System.Windows.DependencyObject, System.Windows.RoutedEvent) at System.Windows.BroadcastEventHelper.BroadcastLoadedEvent(System.Object) at MS.Internal.LoadedOrUnloadedOperation.DoWork() at System.Windows.Media.MediaContext.FireLoadedPendingCallbacks() at System.Windows.Media.MediaContext.FireInvokeOnRenderCallbacks() at System.Windows.Media.MediaContext.RenderMessageHandlerCore(System.Object) at System.Windows.Media.MediaContext.RenderMessageHandler(System.Object) at System.Windows.Media.MediaContext.Resize(System.Windows.Media.ICompositionTarget) at System.Windows.Interop.HwndTarget.OnResize() at System.Windows.Interop.HwndTarget.HandleMessage(MS.Internal.Interop.WindowMessage, IntPtr, IntPtr) at System.Windows.Interop.HwndSource.HwndTargetFilterMessage(IntPtr, Int32, IntPtr, IntPtr, Boolean ByRef) at MS.Win32.HwndWrapper.WndProc(IntPtr, Int32, IntPtr, IntPtr, Boolean ByRef) at MS.Win32.HwndSubclass.DispatcherCallbackOperation(System.Object) at System.Windows.Threading.ExceptionWrapper.InternalRealCall(System.Delegate, System.Object, Int32) at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(System.Object, System.Delegate, System.Object, Int32, System.Delegate) at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(System.Windows.Threading.DispatcherPriority, System.TimeSpan, System.Delegate, System.Object, Int32) at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr, Int32, IntPtr, IntPtr) at MS.Win32.UnsafeNativeMethods.ShowWindow(System.Runtime.InteropServices.HandleRef, Int32) at System.Windows.Window.ShowHelper(System.Object) at System.Windows.Window.Show() at Squirrel.Update.AnimatedGifWindow+<>c__DisplayClass1_0.<ShowWindow>b__0() at System.Threading.ThreadHelper.ThreadStart_Context(System.Object) at System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean) at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean) at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object) at System.Threading.ThreadHelper.ThreadStart()</Data> 
  </EventData>
  </Event>

![install-spinner](https://user-images.githubusercontent.com/3494095/42283982-bc8269e8-7fc8-11e8-9ced-aafd6a812526.gif)
![install-spinner_issue](https://user-images.githubusercontent.com/3494095/42283983-bcd74eb8-7fc8-11e8-9986-4a1413f5962d.gif)

Is there any specific dimension or any rules to have installation animation/.gif files. After reverting default .gif file my app installed without any issue.

**Comment by b-zurg** [comment]
I'm almost 100% this issue is not related to the gif you have.

I just tried it with the following squirrel maker configuration in electron-forge.  Perhaps an update has since fixed the issue?

```js
  makers: [
    {
      name: "@electron-forge/maker-squirrel",
      config: {
        loadingGif: "build/icon2.gif",
        setupIcon: "build/icon.ico"
      }
    },
  ],
```

Anyhow this might be a closable issue.


Pretty fun loading gif by the way!

**Comment by rahulbm** [comment]
Sorry for the delay in response, the issue was with .gif file dimensions I just resized it with reference to the default .gif file and it works without any issues.

**Comment by manths** [comment]
> Sorry for the delay in response, the issue was with .gif file dimensions I just resized it with reference to the default .gif file and it works without any issues.

then what is that size? could you tell us?
