### ISSUE TITLE
documentation request: how to use `signWithParams`

### ISSUE THREAD

**Issue by benjtinsley** [electron/windows-installer#258]
the documentation is scant on what to pass in here. is there something this is based off of that can be a reference? it is not clear what to use here or what the available params are.

any help would be useful, thanks

**Comment by alex-drocks** [comment]
Hey you're right. I was in the blue also...
I found that: https://docs.microsoft.com/en-us/windows/win32/seccrypto/signtool
and was able to manually sign my app with Visual Studio > tools > commandline > developper command line using examples they provide in the bottom of the web page.

But when I use the same command in the signWithParams, the electron build fails
