### ISSUE TITLE
Unable to build windows installer

### ISSUE THREAD

**Issue by ellyyiga** [electron/windows-installer#269]
Here is my electron-builder file
`var electronInstaller = require('electron-winstaller');

resultPromise = electronInstaller.createWindowsInstaller({
    appDirectory: './app',
    outputDirectory: './build/win32',
    authors: 'Horizon',
    setupIcon: './build/icon.ico',
    exe: 'my-app-32.exe'
  });

resultPromise.then(() => console.log("Installer successfully created!"), (e) => console.log(`No dice: ${e.message}`));`

When i run this script, i run into the error
`
No dice: Failed with exit code: 2148734720
Output:
`
Nothing in the Output
Need help here
Node: v8.12.0
npm: v6.4.1
electron: v1.6.11

**Comment by alexanderturinske** [comment]
Duplicates #197
