### ISSUE TITLE
Cannot Build Windows Installer Exit Code 1

### ISSUE THREAD

**Issue by nickabond** [electron/windows-installer#270]
I'm currently running into an issue with building the Windows Installer. When I try and build the installer I get this issue when running this code

SET DEBUG=electron-windows-installer:* & node build.js

```
 electron-windows-installer:spawn Spawning c:\Users\Nick\Desktop\New-Lab-Scale-Programs\hydro-lab-scale-2\node_modules\electron-winstaller\vendor\nuget.exe pack C:\Users\Nick\AppData\Local\Temp\si-11891-12640-1wcyjf7.btxqlrf6r\electron_quick_start.nuspec -BasePath ./electron_quick_start-win32-x64 -OutputDirectory C:\Users\Nick\AppData\Local\Temp\si-11891-12640-1wcyjf7.btxqlrf6r -NoDefaultExcludes +7ms

No dice: Failed with exit code: 1
Output:
Attempting to build package from 'electron_quick_start.nuspec'.
File not found: 'myapp.exe'.
```

Seems to fail once it gets to nuget.exe?

This is my build.js code:

```
var electronInstaller = require('electron-winstaller');

resultPromise = electronInstaller.createWindowsInstaller({
    appDirectory: './electron_quick_start_win32_x64',
    outputDirectory: './myinstallers',
    authors: 'TSC',
    exe: 'myapp.exe'
  });

resultPromise.then(() => console.log("It worked!"), (e) => console.log(`No dice: ${e.message}`));
```

Electron   3.0.2
Node       10.2.0
Chromium   66.0.3359.181

Also here's my package.json if there is something wrong in there:

```
{
  "name": "electron_quick_start",
  "version": "1.0.0",
  "description": "A minimal Electron application",
  "main": "main.js",
  "scripts": {
    "start": "electron .",
    "dist": "build"
  },
  "repository": "https://github.com/electron/electron-quick-start",
  "keywords": [
    "Electron",
    "quick",
    "start",
    "tutorial",
    "demo"
  ],
  "author": "GitHub",
  "license": "CC0-1.0",
  "devDependencies": {
    "electron": "^3.0.2",
    "electron-rebuild": "^1.8.2"
  },
  "dependencies": {
    "debug": "^4.0.1",
    "electron-builder": "^20.28.4",
    "electron-squirrel-startup": "^1.0.0",
    "electron-winstaller": "^2.7.0",
    "node-gyp": "^3.8.0",
    "python": "0.0.4",
    "serialport": "^7.0.2"
  }
}
```

**Comment by alexanderturinske** [comment]
In your `resultPromise` variable, you are still using `exe:  'myapp.exe` instead of your `settings`. Actually, I do not see you using the `settings` variable anywhere.

**Comment by nickabond** [comment]
@alexanderturinske Sorry I wasn't actually using the settings variable (it was commented out in my code). I have updated my post to reflect that. The issue persists either way. Anything else you can see wrong with the code?

**Comment by alexanderturinske** [comment]
Ah, thanks. Just for clarification, what is the name and filepath to your app `exe`? Based on the information above it should be `./electron_quick_start_win32_x64/myapp.exe`; is that correct?

**Comment by nickabond** [comment]
Excellent observation @alexanderturinske! I had thought that was the output name I was choosing for the .exe and not the one I was inputting. Thanks very much, it works now!

**Comment by tenshouuu** [comment]
I have the same problem but i see only: 
```
DEBUG=electron-windows-installer:* node winstaller.js 
creating windows installer
  electron-windows-installer:main Using Mono: 'mono' +0ms
  electron-windows-installer:main Using Wine: 'wine' +0ms
  electron-windows-installer:main Created NuSpec file:
  electron-windows-installer:main ﻿<?xml version="1.0" encoding="utf-8"?>
  electron-windows-installer:main <package xmlns="http://schemas.microsoft.com/packaging/2010/07/nuspec.xsd">
  electron-windows-installer:main   <metadata>
  electron-windows-installer:main     <id>hypercop-dekstop</id>
  electron-windows-installer:main     <title>hypercop</title>
  electron-windows-installer:main     <version>0.0.1</version>
  electron-windows-installer:main     <authors>OFTE</authors>
  electron-windows-installer:main     <owners>OFTE</owners>
  electron-windows-installer:main     <iconUrl>https://raw.githubusercontent.com/atom/electron/master/atom/browser/resources/win/atom.ico</iconUrl>
  electron-windows-installer:main     <requireLicenseAcceptance>false</requireLicenseAcceptance>
  electron-windows-installer:main     <description></description>
  electron-windows-installer:main     <copyright>Copyright © 2018 OFTE</copyright>
  electron-windows-installer:main   </metadata>
  electron-windows-installer:main   <files>
  electron-windows-installer:main     <file src="locales/**" target="lib/net45/locales" />
  electron-windows-installer:main     <file src="resources/**" target="lib/net45/resources" />
  electron-windows-installer:main     <file src="*.bin" target="lib/net45" />
  electron-windows-installer:main     <file src="*.dll" target="lib/net45" />
  electron-windows-installer:main     <file src="*.pak" target="lib/net45" />
  electron-windows-installer:main     <file src="*.exe.sig" target="lib/net45" />
  electron-windows-installer:main     <file src="Update.exe" target="lib/net45/squirrel.exe" />
  electron-windows-installer:main     <file src="icudtl.dat" target="lib/net45/icudtl.dat" />
  electron-windows-installer:main     <file src="LICENSE" target="lib/net45/LICENSE" />
  electron-windows-installer:main     <file src="hypercop.exe" target="lib/net45/hypercop.exe" />
  electron-windows-installer:main   </files>
  electron-windows-installer:main </package>
  electron-windows-installer:main  +36ms
  electron-windows-installer:spawn Spawning mono /home/devel/Documents/projects/Hyperbot/hyperbot-desktop/node_modules/electron-winstaller/vendor/nuget.exe pack /tmp/si-118912-3533-rxili0.ax01o/hypercop-dekstop.nuspec -BasePath builds/hypercop-win32-ia32/ -OutputDirectory /tmp/si-118912-3533-rxili0.ax01o -NoDefaultExcludes +5ms
Failed with exit code: 1
Output:
Attempting to build package from 'hypercop-dekstop.nuspec'.
Description is required.

```
my script:
 `const createWindowsInstaller = require('electron-winstaller').createWindowsInstaller
const path = require('path')

getInstallerConfig()
	.then(createWindowsInstaller)
	.catch((error) => {
		console.error(error.message || error)
		process.exit(1)
	})

function getInstallerConfig () {
	console.log('creating windows installer')
	const rootPath = path.join('./')
	const outPath = path.join(rootPath, 'builds')

	return Promise.resolve({
		appDirectory: path.join(outPath, 'hypercop-win32-ia32/'),
		authors: 'OFTE',
		noMsi: true,
		outputDirectory: path.join(outPath),
		exe: 'hypercop.exe',
		setupExe: 'hypercop-installer.exe'
	})
}
`
wine --version
wine-3.0.3

mono --version
Mono JIT compiler version 5.10.1.12 (tarball Fri Mar 23 10:14:53 UTC 2018)
Copyright (C) 2002-2014 Novell, Inc, Xamarin Inc and Contributors. www.mono-project.com
	TLS:           __thread
	SIGSEGV:       altstack
	Notifications: epoll
	Architecture:  amd64
	Disabled:      none
	Misc:          softdebug 
	Interpreter:   yes
	LLVM:          supported, not enabled.
	GC:            sgen (concurrent by default)

**Comment by francisfmassaquoijr** [comment]
@alexanderturinske thanks so much for such a brilliant observation I solved mine

**Comment by hamzaaslam76** [comment]
I am facing the same issue
creating windows installer
message Failed with exit code: 1
Output:
Attempting to build package from 'electron_app.nuspec'.
A description is required.
`
const createWindowsInstaller = require('electron-winstaller').createWindowsInstaller
const path = require('path')

getInstallerConfig()
  .then(createWindowsInstaller)
  .catch((error) => {
    console.error("message",error.message || error)
    process.exit(1)
  })

function getInstallerConfig () {
  console.log('creating windows installer')
  const rootPath = path.join('./')
  //const outPath = path.join(rootPath, 'release-builds')

  return Promise.resolve({
    appDirectory:  './electron_app-win32-x64',
    authors: 'hamza',
    noMsi: true,
    outputDirectory: './windows-installer',
    exe: './electron_app-win32-x64/electron_app.exe',
   // setupExe: 'ElectronTutorialAppInstaller.exe'
    //setupIcon: path.join(rootPath, 'assets', 'icons', 'win', 'icon.ico')
  })
}
Also here's my package.json if there is something wrong in there:
`
{
  "name": "electron_app",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "electron-dev": "concurrently \"cd resource && npm run build && node server.js\"// \"wait-on http://localhost:4000 && electron .\"",
    "test": "electron .",
    "electron-build": "electron-packager . "
  },
  "author": "",
  "license": "ISC",
  "build": {
    "asar": true,
    "appId": "com.myapp.electron"
  },
  "dependencies": {
    "camelcase": "^6.2.0",
    "concurrently": "^6.2.0",
    "cors": "^2.8.5",
    "electron-builder": "^22.11.7",
    "electron-is-dev": "^2.0.0",
    "electron-packager": "^15.2.0",
    "electron-squirrel-startup": "^1.0.0",
    "express": "^4.17.1",
    "python": "^0.0.4",
    "serialport": "^9.2.0",
    "wait-on": "^6.0.0",
    "which-module": "^2.0.0"
  },
  "devDependencies": {
    "electron": "^13.1.6",
    "electron-rebuild": "^2.3.5",
    "electron-winstaller": "^5.0.0"
  }
}

> 
folder structure

![2021-07-12_23-56-28](https://user-images.githubusercontent.com/71928885/125341646-44ca9680-e36d-11eb-9f77-16cde7f9e1d7.png)

**Comment by AntoniKozlov** [comment]
@hamzaaslam76 Hi, Did you find solution?
