### ISSUE TITLE
Signing with an EV Code Signing Certificate

### ISSUE THREAD

**Issue by frederikbosch** [electron/windows-installer#280]
I want to sign my electron application. So I purchased this EV Code Signing Certificate, which comes on a USB dongle. I managed to run the [Safenet Authentication Client on Ubuntu](https://knowledge.digicert.com/content/dam/digicertknowledgebase/attachment/solution/SO28683/SafeNet%20Authentication%20Client_9.0_Users_Guide.pdf).

However, my question is "what's next?". According to the docs of this lib I need pfx or p12 file to sign the code. So how do I generate them using the USB dongle? I can only export a cer file. After reading a bit I am not sure if that is what I want anyway. If my feeling is correct how should I sign the code otherwise? Should I use `signWithParams`? If so, I would love to know what I should pass in there, or some direction to it.

Since I have no idea where else to put my question, I am posting it in here. Hoping someone is willing to point me into the right direction.

**Comment by Galkon** [comment]
I'd like to know this too.

**Comment by timsatterfield** [comment]
I am in a similar situation (however I develop on a Mac). Here's a manual workaround:

* Generate your windows builds via docker, where `dist_windows` is defined in your package.json scripts section:
```
#!/bin/bash
docker run --rm -ti -v ${PWD}:/project -v ${PWD##*/}-node-modules:/project/node_modules -v ~/.electron:/root/.electron electronuserland/electron-builder:wine npm run dist_windows
```

Code sign on a Virtual Box Windows VM

Setup:
* You can download images here https://developer.microsoft.com/en-us/microsoft-edge/tools/vms/
* Install the Safenet Auth client on both the host and vm.
* On the Windows VM, install the Digicert utility https://www.digicert.com/util/
* Enable your VM to access your USB Ports. You may need to setup a generic device filter.
* Configure a shared folder to copy files as needed between your host and vm

Codesign:
* Now finally plug in your EV USB key.
* Open Safenet Auth Client
* Open Digicert Utility
* Select files to sign

Caveats:  This is pretty convoluted and only signs the main installer.  If your users try to uninstall, they will get an unknown developer warning on 'update.exe'

Would love to 1.) Be able to automate this, 2.) codesign the other files within the app so users don't get any unknown developer warnings.

**Comment by frederikbosch** [comment]
I ended up with something similar to this.
https://gist.github.com/frederikbosch/68757c45f7fd53c67c3924657f65e2d9

**Comment by frederikbosch** [comment]
https://www.electron.build/tutorials/code-signing-windows-apps-on-unix
