### ISSUE TITLE
version 2.7.0 does not include Squirrel 1.9.0 

### ISSUE THREAD

**Issue by bitdisaster** [electron/windows-installer#287]
As far as I can tell version 2.7.0 was supposed to use Squirrel 1.9.0. However, only Squirrel.exe is updated to 1.9.0 while Update.exe is still 1.7.9. Looking at the module code, only Update.exe is used to package the installer. So the resulting installer will continue to run on Squirrel 1.7.9.

**Comment by MarshallOfSound** [comment]
Closing as `3.0.1` has been released with `1.9.1`
