### ISSUE TITLE
Icon inconsistency

### ISSUE THREAD

**Issue by jkudish** [electron/windows-installer#29]
Pretty minor thing, but `iconUrl` accepts a URL whereas `setupIcon` accepts a local resource. It would be nice if they could both accept a URL.

Also this could be better documented (happy to submit a PR for that later)

**Comment by lukeapage** [comment]
yeah I noticed this and didn't understand why it needed to be a URL.

Looking at https://docs.nuget.org/create/nuspec-reference I can see it is used for the manage nuget packages dialogue - if its not used anywhere else, is this option only for people publishing on nuget?

**Comment by astoilkov** [comment]
Anyone have answers to these questions? I am also wondering.

**Comment by develar** [comment]
Related: https://github.com/electronjs/grunt-electron-installer/issues/73

**Comment by develar** [comment]
NuGet issue — https://github.com/NuGet/Home/issues/352

**Comment by havenchyk** [comment]
Cannot be fixed since it's a nuget issue.
