### ISSUE TITLE
Upgrade fs-extra to ^7.0.1

### ISSUE THREAD

**Issue by malept** [electron/windows-installer#291]
This module uses a pretty old version of `fs-extra`, and a bunch of the utility code is no longer necessary if we upgrade.

https://github.com/electron/windows-installer/blob/5954c8e14b5d3bccfcb73e99a403be903e691447/src/fs-utils.js#L10-L16

:point_up: `fs-extra` functions have been promisified for a while, this is no longer necessary. _(Probably need to keep `createTempDir` though.)_

https://github.com/electron/windows-installer/blob/5954c8e14b5d3bccfcb73e99a403be903e691447/src/fs-utils.js#L18-L30

:point_up: [`fs.pathExists`](https://github.com/jprichardson/node-fs-extra/blob/master/docs/pathExists.md), well, exists.

It'd be worth auditing the rest of this module to make see if we can use any of the utility functions from `fs-extra`, like `fs.readJson`.

CC: @carterbs, as you mentioned in the Atom Slack that you wanted to take on some of the upgrades.

**Comment by carterbs** [comment]
Sounds great. Give me a couple of days. I'm willing to commit to Saturday afternoon.

**Comment by malept** [comment]
FIxed in #293.
