### ISSUE TITLE
Why does it produce a tgz file containing my source code?

### ISSUE THREAD

**Issue by J-Cake** [electron/windows-installer#297]
I've got the following script:

```javascript 
const winstaller = require('electron-winstaller');
const path = require('path');

resultPromise = winstaller.createWindowsInstaller({
    appDirectory: './release-builds/<Packaged App Name>-win32-ia32/',
    outputDirectory: '/release-builds/installers',
    authors: '<Devs names>',
    exe: '<Output>.exe',
    loadingGif: path.join(__dirname, 'src', 'res', 'Installer-backdrop.gif'),
    iconUrl: path.join(__dirname, 'src', 'res', 'favicon.ico')
});

resultPromise.then(() => console.log("It worked!"), (e) => console.log(`No dice: ${e.message}`));
```

and when I run it, nothing but a `tgz` file in my root dir. When extracting it, I get nothing but the *unbuilt* react app. Mind you, I used the `electron-packager` on the output of the react build but still, only a `.tgz`. Why?

**Comment by kaatt** [comment]
For posterity, this happened to me because I set `scripts.pack` in `package.json` to my electron build command and `npm/yarn pack` is a predefined command: https://yarnpkg.com/lang/en/docs/cli/pack/

**Comment by J-Cake** [comment]
Oh gosh this was a while ago, I don't even have that project anymore
