### ISSUE TITLE
NPM won't install winstaller. 

### ISSUE THREAD

**Issue by Codeer12** [electron/windows-installer#298]
Whenever I attempt to install it it says this. 
`npm WARN registry Unexpected warning for https://registry.npmjs.org/: Miscellaneous Warning ENODATA: Cache input stream was empty
npm WARN registry Using stale package data from https://registry.npmjs.org/ due to a request error during revalidation.
npm ERR! code EINTEGRITY
npm ERR! errno EINTEGRITY
npm ERR! Invalid response body while trying to fetch https://registry.npmjs.org/minimatch: Integrity verification failed for sha512-118N9Z7gYyrDPeepyQq4K+6cB9HJzfHjN99FtUzE0+I97Aagz1kOiXZZ7xRBQhjbBIXYpb6cw39nghbMF5bVww== `

**Comment by malept** [comment]
This isn't a problem with this module, but a problem with NPM or your network.
