### ISSUE TITLE
FooBarSetup.exe installing screen appears all the time.

### ISSUE THREAD

**Issue by lmatteis** [electron/windows-installer#30]
The .exe is generated correctly although it has a "Setup" extension and every time I open it there's a weird greenish installing screen that appears. Is there a way to simply obtain the `.exe` of everything? Also it's unclear what the installer actually does.

**Comment by paulcbetts** [comment]
I'm not sure I understand what you're asking

**Comment by lmatteis** [comment]
When I double click the .exe I get an installer loading window which I don't know what it does.

**Comment by jkudish** [comment]
Sounds like the same issue I reported in #28

**Comment by lukeapage** [comment]
@lmatteis please can you confirm what OS you are using to build in?

**Comment by havenchyk** [comment]
It's not an issue, but the expected behavior.
