### ISSUE TITLE
dot being removed from file name 

### ISSUE THREAD

**Issue by servappio** [electron/windows-installer#314]
I'm trying to make an installer with the version number 4.0.0-beta.1, the installer file is correct but the nupkg file is exporting as 4.0.0-beta1 (missing dot). I'm guessing that its the function convertVersion that replaces any dots in the version.

```
export function convertVersion(version: string): string {
  const parts = version.split('-');
  const mainVersion = parts.shift();

  if (parts.length > 0) {
    return [mainVersion, parts.join('-').replace(/\./g, '')].join('-');
  } else {
    return mainVersion as string;
  }
}
```

Is there a way to not do this?

**Comment by bchmnn** [comment]
@servappio I currently having the same struggle. Did you come up with a solution?
