### ISSUE TITLE
Can't Specify Installation Directory

### ISSUE THREAD

**Issue by djbreen7** [electron/windows-installer#324]
There doesn't appear to be an option to set the final installation directory. There needs to be an option like `installDirectoryName`. Currently, the application always installs to:

`'%USERPROFILE%/AppData/Local/' + 'require(package.json).name'`

I understand that the first segment is a requirement, but I'd really like to change the second segment without having to manipulate the package.json.

Use Case:
We have an application that we allows third-party businesses to white-label. The name in the package.json is generic, whereas we need the application name and related files/folders to be reflective of the business name.

**Comment by paulosborne** [comment]
I believe this is more to do with the Squirrel.Windows framework than windows-installer, check out the [installation process](https://github.com/Squirrel/Squirrel.Windows/blob/master/docs/using/install-process.md#install-location) which briefly mentions it.
