### ISSUE TITLE
iconUrl: not working (file is at correct ICO format)

### ISSUE THREAD

**Issue by onelsonic** [electron/windows-installer#330]
Hi there I keep getting the following error when I try to add the iconUrl: for my build:

```
Well, sometimes you are not so lucky: Failed with exit code: 1
Output:
Attempting to build package from 'myAPP.nuspec'.
Invalid URI: The format of the URI could not be determined.
```

**Comment by Moonie68** [comment]
Did you fix this? PLEASE TELL ME HOW! I can't get it to work, no matter how I change the code! 💢 so frustrating...

**Comment by someplacee** [comment]
`iconUrl` needs to be a URL to the file on GitHub, just upload your file on your website or on GitHub and enter a full Path.
