### ISSUE TITLE
iconUrl  parameter has not effect 

### ISSUE THREAD

**Issue by onelsonic** [electron/windows-installer#332]
iconUrl is not working at all. The Programs and Features is not changing.

> URL to an ICO file to use as the application icon (displayed in  Control Panel > Programs and Features). Defaults to the Atom icon.

here is what we have : 
<img width="264" alt="2020-02-29 14_50_25-Programs and Features" src="https://user-images.githubusercontent.com/53947594/75608930-41ca5f80-5b04-11ea-9766-07d56e986291.png">

**Comment by onelsonic** [comment]
also why using a web URL and not a local file ?
either case none of them works.

**Comment by malept** [comment]
> also why using a web URL and not a local file ?

See "Icon URL" at: https://github.com/Squirrel/Squirrel.Windows/blob/de5baa93a134ac24fd5bf9172d3e457ac27e0b7a/docs/using/nuget-package-metadata.md#L15

**Comment by onelsonic** [comment]
iconUrl parameter still doesn't work

**Comment by someplacee** [comment]
i have the same problem.

**Comment by malept** [comment]
I can't reproduce this behavior. I set `iconUrl` to `https://www.google.com/favicon.ico` and that's what showed up as the icon in Control Panel ➡️ Programs ➡️ Programs and Features ➡️ Uninstall or change a program on Windows 10 Home.
