### ISSUE TITLE
The msi installer doesn't create a wizard

### ISSUE THREAD

**Issue by abpbackup** [electron/windows-installer#364]
Hi. 
I don't know if it is an issue, but I expected to get a msi installer with a wizard with license agreement and all the stuff you can find in most of the msi installer out there. The installer DOES install the app but it closes without any confirmation message.
Thanks.

**Comment by malept** [comment]
If you need a customizable MSI-based installer, consider using [`electron-wix-msi`](https://github.com/felixrieseberg/electron-wix-msi) instead.
