### ISSUE TITLE
node build.js don't have any response 

### ISSUE THREAD

**Issue by Flyooofly** [electron/windows-installer#390]
I run the node build.js ,but don;t have any response 
At first I thought it was running, but after waiting for an hour there was no result.I have determined the path is ok I don't know why this is the case. Below is my code. Please take a look, thank you.
![image](https://user-images.githubusercontent.com/31236750/124374780-b2712580-dcd0-11eb-8c35-48c6f12259e8.png)

**Comment by fingercoder** [comment]
sames as mine

**Comment by Flyooofly** [comment]
I had solved .You need to wait. I use the 3 hours.…Then I get the error that the path is too long.Then I add the&nbsp; --asar to the electron-packager&nbsp; command&nbsp; and I move my project to the root doctors C:\。Then I solve this.



---Original---
From: ***@***.***&gt;
Date: Wed, Jul 14, 2021 16:18 PM
To: ***@***.***&gt;;
Cc: "JackoooooR"<2207326681@***@***.***&gt;;
Subject: Re: [electron/windows-installer] node build.js don't have any response  (#390)




 
sames as mine

**Comment by fingercoder** [comment]
sorry. some wrong in your answer
![image](https://user-images.githubusercontent.com/29332312/125591258-1ee7ad7b-3a50-463a-9db6-b003d161db50.png)
your mine is that we need add --asar into my electron-packager command

**Comment by fingercoder** [comment]
by the way ,if you are chinese,please answer by chinsese

**Comment by Flyooofly** [comment]
"package": "electron-packager . XX --platform=win32  --arch=x64 --win --out C:\\project\\ --electron-version 1.7.10 --asar  --icon=loog.ico"
当时看到一种方案是把文件放到根目录下，因为运行很长时间以后会报错说什么路径太深超过了长度。我把项目搬到了根目录下但仍然不行，然后又看到他们的这种方案，在eletron打包的命令这加一个--asar，然后我执行node build.js后五分钟左右就出结果了。

**Comment by fingercoder** [comment]
> ```
> "package": "electron-packager . XX --platform=win32  --arch=x64 --win --out C:\\project\\ --electron-version 1.7.10 --asar  --icon=loog.ico"
> ```
> 
> 当时看到一种方案是把文件放到根目录下，因为运行很长时间以后会报错说什么路径太深超过了长度。我把项目搬到了根目录下但仍然不行，然后又看到他们的这种方案，在eletron打包的命令这加一个--asar，然后我执行node build.js后五分钟左右就出结果了。

老哥辛亏了，我试试吧
