### ISSUE TITLE
installer doesn't copy extra resources directories during installation

### ISSUE THREAD

**Issue by d9k** [electron/windows-installer#43]
Hi! I have an issue with creating windows installer with electron-builder (see https://github.com/loopline-systems/electron-builder/issues/252) but electron-builder developer asked me to recreate issue here.
The problem is: I use two-package.json project layout (`package.json` and `app/package.json`) and extra resources folders (for example with dlls) are not copied to installation path during installer run. Extra files are copied, there is no problems with them, but extra folders are not. 

Also tried to move folders with dlls into `app` folder, but haven't succeed: dlls folders are packaged into `resources/app.asar` but can't be found and loaded on electron application startup.

**Comment by d9k** [comment]
@develar I unpacked "resources/app.asar" and found extra resources folders here!

**Comment by develar** [comment]
We copy extra resources AFTER electron-packager `pack`.
So, your guess is probably correct, but `windows-installer` code (https://github.com/electronjs/windows-installer/blob/master/src/index.js) is very simple and I don't see who does it.

I hope authors of the windows-installer will help, I can investigate this problem only only 23 March.

**Comment by develar** [comment]
update: No, "found extra resources folders here!" it is totally wrong, I think. It is only because you "Also tried to move folders with dlls into app folder,", right ;) and electron-packager copies it?

**Comment by d9k** [comment]
@develar, yes, sorry, false-positive.. I deleted files but kept folders by mistake and then I check only folders existence in app.asar :laughing:

**Comment by develar** [comment]
I believe that we should somehow use `asar-unpack-dir` (see electron-packager options), but sorry, I don't have time to investigate and fix it right now.

**Comment by d9k** [comment]
@develar thanks anyway. As soon as extra files from package root are copied,  I'll implement temporary hacky solution in squirrel installer hook: move files to the needed location after installation.

**Comment by marcopiraccini** [comment]
Probably a more general solution would be to customize the `template.nuspec`. Adding -for instance:

```
	<file src="exe/**" target="lib/net45" />
```
...will add the folder as you expected. Putting hte `exe` folder outside the `app` folder will also avoid to have it put into `app.asar`. 

To obtain that, it would be great to have the ability of using custom templates.

**Comment by develar** [comment]
@marcopiraccini Thanks a lot for advice. I will fix it next week.

**Comment by d9k** [comment]
@develar directories copying fixed at 3.0.1, fix confirmed

**Comment by mvkanha** [comment]
@octavian-sandru I am facing same problem
