### ISSUE TITLE
Advanced updating support

### ISSUE THREAD

**Issue by marcopiraccini** [electron/windows-installer#46]
Squirrel supports "advanced updating" (e.g. asking the user if he wants to download the update, apply the update, etc), see: https://github.com/Squirrel/Squirrel.Windows/blob/master/docs/using/update-manager.md#advanced-updating

I'd like to ask user if he wants to download and apply an update. How that can be managed? I guess that app is spawn with `--squirrel-updated` parameter when the update is done (so update already downloaded and installed). It's correct?  

If so, how that can be obtained?

**Comment by antoinepairet** [comment]
Please see: 
- http://www.mylifeforthecode.com/creating-a-windows-distribution-of-an-electron-app-using-squirrel/
- http://stackoverflow.com/questions/30105150/handle-squirrels-event-on-an-electron-app

**Comment by MarshallOfSound** [comment]
The above comment points people in a good direction, basically this UI needs to be created / managed by you using the Electron `autoUpdater` events.
