### ISSUE TITLE
How to sign additional binaries

### ISSUE THREAD

**Issue by norbertkovacs95** [electron/windows-installer#480]
I have an electron project which integrates a node library that uses native modules. When I install the signed app, and require the .node file, and access error is thrown since that file is not signed. 

Is there any way to sign these binaries as well? 

Thanks in advance for the help.

**Comment by norbertkovacs95** [comment]
I managed to solve this issue by first packaging the app (`electron-froge package`), then by using the signtool.exe shipped by windows-installer signing the binaries manually, and finally running `electron-forge --skip-package flag`.

**Comment by norbertkovacs95** [comment]
I managed to solve this issue by first packaging the app (`electron-forge package`), then by using the signtool.exe shipped by windows-installer signing the binaries manually, and finally running `electron-forge make --skip-package`.

**Comment by MarshallOfSound** [comment]
> I managed to solve this issue by first packaging the app (`electron-forge package`), then by using the signtool.exe shipped by windows-installer signing the binaries manually, and finally running `electron-forge make --skip-package`.

You could do this smoothly in a single step if you ran `signtool.exe` inside a `postPackage` step:
https://www.electronforge.io/config/hooks#postpackage
