### ISSUE TITLE
You must install both Mono and Wine on non-Windows

### ISSUE THREAD

**Issue by Luncher** [electron/windows-installer#50]
[luncher@localhost build]$ ./build_installer.sh 
You must install both Mono and Wine on non-Windows
[luncher@localhost build]$ cat build_installer.sh 
#!/usr/bin/env node

var electronInstaller = require('electron-winstaller');

electronInstaller.createWindowsInstaller({
    appDirectory: './package/HolaStudio-win32-x64/',
    outputDirectory: './installer/',
    authors: 'Holaverse Tech Inc. ',
    exe: 'HolaStudio.exe'
}).then(function() {
    console.log("build done");
}, function(err) {
    console.log(err.message);
});

Both tools are necessary to install it? My computer is fedora system.

**Comment by havenchyk** [comment]
@Luncher yes, both are needed on every non-windows system.
