### ISSUE TITLE
Could not load file or assembly 'Microsoft.Build`

### ISSUE THREAD

**Issue by Luncher** [electron/windows-installer#51]
[luncher@localhost build]$ ./build_installer.sh 
Failed with exit code: 1
Output:
Could not load file or assembly 'Microsoft.Build, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies.

[luncher@localhost build]$ cat build_installer.sh 
# !/usr/bin/env node

var electronInstaller = require('electron-winstaller');

electronInstaller.createWindowsInstaller({
    appDirectory: './package/HolaStudio-win32-x64/',
    outputDirectory: './installer/',
    authors: 'Holaverse Tech Inc. ',
    exe: 'HolaStudio.exe'
}).then(function() {
    console.log("build done");
}, function(err) {
    console.log(err.message);
});

**Comment by MarshallOfSound** [comment]
It looks like you are missing some Wine or Mono dependencies.  Did you resolve this issue?

**Comment by MarshallOfSound** [comment]
As the reporter has not responded to the request for additional information this issue will be closed.  If further information can be provided at some point in the future, comment on this issue with the requested information and if appropriate the issue will be reopened.

**Comment by tHBp** [comment]
Running into the same error. Using CentOS 7 with Mono and Wine installed.

```
Error: Failed with exit code: 1
Output:

Unhandled Exception:
System.IO.FileNotFoundException: Could not load file or assembly 'WindowsBase, Version=4.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35' or one of its dependencies.
File name: 'WindowsBase, Version=4.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35'
[ERROR] FATAL UNHANDLED EXCEPTION: System.IO.FileNotFoundException: Could not load file or assembly 'WindowsBase, Version=4.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35' or one of its dependencies.
File name: 'WindowsBase, Version=4.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35'
```

Can we reopen this? Let me know if additional information is needed.

**Comment by sbuller** [comment]
I ran into an issue with WindowsBase not loading during a build with electron-forge. I'm running on Fedora 30, with mono and wine already installed.

I resolved the issue by installing 'nuget'. I notice that the install also pulled in mono-winfx.
