### ISSUE TITLE
Error on OS X: "System.DllNotFoundException: msdelta.dll"

### ISSUE THREAD

**Issue by feross** [electron/windows-installer#61]
```
$ wine --version
wine-1.8.1
```

```
$ mono --version
Mono JIT compiler version 4.2.3 (Stable 4.2.3.4/832de4b Wed Mar 30 13:57:48 PDT 2016)
Copyright (C) 2002-2014 Novell, Inc, Xamarin Inc and Contributors. www.mono-project.com
	TLS:           normal
	SIGSEGV:       altstack
	Notification:  kqueue
	Architecture:  amd64
	Disabled:      none
	Misc:          softdebug 
	LLVM:          supported, not enabled.
	GC:            sgen
```

Any ideas?

```
$ DEBUG=electron-windows-installer:main npm run package -- win32 
  electron-windows-installer:main Using Mono: '/usr/local/bin/mono' +0ms
  electron-windows-installer:main Using Wine: '/usr/local/bin/wine' +2ms
  electron-windows-installer:main Created NuSpec file:
<?xml version="1.0" encoding="utf-8"?>
<package xmlns="http://schemas.microsoft.com/packaging/2010/07/nuspec.xsd">
  <metadata>
    <id>WebTorrent</id>
    <title>WebTorrent</title>
    <version>0.2.0</version>
    <authors>The WebTorrent Project</authors>
    <owners>The WebTorrent Project</owners>
    <iconUrl>https://raw.githubusercontent.com/feross/webtorrent-desktop/master/static/WebTorrent.ico</iconUrl>
    <requireLicenseAcceptance>false</requireLicenseAcceptance>
    <description>WebTorrent</description>
    <copyright>Copyright © 2016 The WebTorrent Project</copyright>
  </metadata>
  <files>
    <file src="locales/**" target="lib/net45/locales" />
    <file src="resources/**" target="lib/net45/resources" />
    <file src="*.bin" target="lib/net45" />
    <file src="*.dll" target="lib/net45" />
    <file src="*.pak" target="lib/net45" />
    <file src="Update.exe" target="lib/net45/squirrel.exe" />
    <file src="icudtl.dat" target="lib/net45/icudtl.dat" />
    <file src="LICENSE" target="lib/net45/LICENSE" />
    <file src="WebTorrent.exe" target="lib/net45/WebTorrent.exe" />
  </files>
</package>
 +53ms
  electron-windows-installer:main Attempting to build package from 'WebTorrent.nuspec'.
Successfully created package '/var/folders/n9/tqh670d16c3bd5853qgbvz1w0000gn/T/si-11635-82019-17kbzp6/WebTorrent.0.2.0.nupkg'.
 +24s
  electron-windows-installer:main  +17s
Failed with exit code: 255
Output:
System.DllNotFoundException: msdelta.dll
  at (wrapper managed-to-native) DeltaCompressionDotNet.MsDelta.NativeMethods:CreateDelta (DeltaCompressionDotNet.MsDelta.FileTypeSet,long,long,string,string,string,string,DeltaCompressionDotNet.MsDelta.DeltaInput,intptr,DeltaCompressionDotNet.MsDelta.HashAlgId,string)
  at DeltaCompressionDotNet.MsDelta.MsDeltaCompression.CreateDelta (System.String oldFilePath, System.String newFilePath, System.String deltaFilePath) <0x1063ef5e0 + 0x0007b> in <filename unknown>:0 
  at Squirrel.DeltaPackageBuilder.createDeltaForSingleFile (System.IO.FileInfo targetFile, System.IO.DirectoryInfo workingDirectory, System.Collections.Generic.Dictionary`2 baseFileListing) <0x1063eea40 + 0x003b0> in <filename unknown>:0 
  at Squirrel.DeltaPackageBuilder.CreateDeltaPackage (Squirrel.ReleasePackage basePackage, Squirrel.ReleasePackage newPackage, System.String outputFile) <0x1063c1dc0 + 0x006f9> in <filename unknown>:0 
  at Squirrel.Update.Program.Releasify (System.String package, System.String targetDir, System.String packagesDir, System.String bootstrapperExe, System.String backgroundGif, System.String signingOpts, System.String baseUrl, System.String setupIcon, Boolean generateMsi) <0x1052a8f60 + 0x00b5a> in <filename unknown>:0 
  at Squirrel.Update.Program.executeCommandLine (System.String[] args) <0x102a10930 + 0x0173e> in <filename unknown>:0 
  at Squirrel.Update.Program.main (System.String[] args) <0x102a0c260 + 0x0027a> in <filename unknown>:0 
```

**Comment by feross** [comment]
This is what is run right before the crash:

```
  electron-windows-installer:spawn Spawning /usr/local/bin/mono /Users/feross/code/webtorrent-desktop/node_modules/electron-winstaller/vendor/nuget.exe pack /var/folders/n9/tqh670d16c3bd5853qgbvz1w0000gn/T/si-11635-82456-7y678c/WebTorrent.nuspec -BasePath /Users/feross/code/webtorrent-desktop/dist/WebTorrent-win32-x64 -OutputDirectory /var/folders/n9/tqh670d16c3bd5853qgbvz1w0000gn/T/si-11635-82456-7y678c -NoDefaultExcludes +16ms
  electron-windows-installer:main Attempting to build package from 'WebTorrent.nuspec'.
Successfully created package '/var/folders/n9/tqh670d16c3bd5853qgbvz1w0000gn/T/si-11635-82456-7y678c/WebTorrent.0.2.0.nupkg'.
 +29s
  electron-windows-installer:spawn Spawning /usr/local/bin/mono /Users/feross/code/webtorrent-desktop/node_modules/electron-winstaller/vendor/SyncReleases.exe -u https://github.com/feross/webtorrent-desktop -r /Users/feross/code/webtorrent-desktop/dist +3ms
  electron-windows-installer:main  +19s
  electron-windows-installer:spawn Spawning /usr/local/bin/mono /Users/feross/code/webtorrent-desktop/node_modules/electron-winstaller/vendor/Update-Mono.exe --releasify /var/folders/n9/tqh670d16c3bd5853qgbvz1w0000gn/T/si-11635-82456-7y678c/WebTorrent.0.2.0.nupkg --releaseDir /Users/feross/code/webtorrent-desktop/dist --loadingGif /Users/feross/code/webtorrent-desktop/static/loading.gif --setupIcon /Users/feross/code/webtorrent-desktop/static/WebTorrent.ico --no-msi +5ms
Failed with exit code: 255
```

**Comment by develar** [comment]
Do you use electron-builder?

**Comment by feross** [comment]
No, I use this package directly.

**Comment by feross** [comment]
You can see how the package is used here: https://github.com/feross/webtorrent-desktop/blob/master/bin/package.js#L264-L285

**Comment by develar** [comment]
Reproduced on OS X. @paulcbetts I have no idea how to fix it and don't see related changes (https://github.com/electron/grunt-electron-installer/issues/90#issuecomment-167831400).

**Comment by voldmar** [comment]
As far as I understood today, we have 64-bit Mono which tries use 32-bit msdelta.dll.so from 32-bit Wine. And we have 32-bit Wine because current XCode can’t build 64-bit Wine. Our life is painful, isn’t it?

Unfortunately have no time to find way to build proper dll

**Comment by develar** [comment]
@voldmar 32-bit mono (official, not from brew) fails as well.

**Comment by havenchyk** [comment]
@paulcbetts could you please have a look?

**Comment by feross** [comment]
@felixrieseberg Might be able to help too.

Is there any chance you guys could help with this? It would make it way easier for developers to build Electron apps for Windows.

This is the last issue standing in the way of being able to build for all three platforms from OS X.

**Comment by develar** [comment]
BTW — I have tried to use only wine (wine includes mono), but it is not possible — it fails on HTTPS requests (yes, I read mono security, but doesn't work) + cannot clean content types xml (weird win exception).

**Comment by develar** [comment]
>  last issue standing in the way of being able to build for all three platforms from OS X.

@feross Unfortunately, no. https://github.com/electron/windows-installer/issues/27#issuecomment-195263824 is not implemented yet.

**Comment by paulcbetts** [comment]
Fixed. I've got some work to do on Squirrel.Windows this week, then we'll put out a new version

**Comment by voldmar** [comment]
@paulcbetts Fixed — as in «we can build Win app on Mac»? Hooray!

**Comment by havenchyk** [comment]
@paulcbetts when are you planning to release the next Squirrel.Windows version?

**Comment by feross** [comment]
@paulcbetts Nice!

> last issue standing in the way of being able to build for all three platforms from OS X.

I don't do code signing for WebTorrent on Windows yet. Still waiting for Comodo to issue my cert. But yeah, guess we still need that.

**Comment by develar** [comment]
>  Comodo to issue my cert

@feross Unrelated: Comodo — OMG, keep me away... Don't want to waste my time and money — startssl.com will send you security code using special letter instead of notary.

**Comment by feross** [comment]
@develar Thanks for pointing out StartSSL. Comodo is terrible and just a disgrace. They're easily the worst company I've ever had to deal with. It's been two weeks of back and forth and I still don't have a cert.

I read on Microsoft's site that only Verisign, Thawte (which is now owned by Verisign), and Comodo can issue code signing certs for Windows. Is that no longer the case?

Looks like StartSSL Class 2 cert can do object code signing for just $60. Is that right?

**Comment by develar** [comment]
@feross Microsoft accepts any "Class 2 Code Signing" certificate. Of course, "required for UEFI, kernel-mode drivers, and LSA certifications" is a special case. For us, to distribute app, standard "Class 2 Code Signing" certificate is enough.

> StartSSL Class 2 cert can do object code signing for just $60

Yes. And you don't need to pay for notary. Special letter (you can receive it only in the post office and your passport/signature are required) is free for you.

**Comment by feross** [comment]
@develar Very handy - thanks.

**Comment by voldmar** [comment]
I just have tried to build an installer under Win 8.1 (from [modern.ie](https://modern.ie) project), but got an error about running `rcedit.exe`. After running `rcedit.exe` from `electron-winstaller` I’ve got message about absence of `msvcp100.dll`.

But, fresh `rcedit.exe` from atom/rcedit#11 resolves this problem. Should I create fresh PR with `rcedit.exe` from atom/rcedit?

**Comment by develar** [comment]
@voldmar I created — https://github.com/electron/windows-installer/pull/69

**Comment by develar** [comment]
Thanks @paulcbetts! electron-builder test passed on OS X, (electron-winstaller-fixed 2.2.1-beta.0 published).

**Comment by develar** [comment]
electron-builder 3.5.1 contains fixed version.

**Comment by voldmar** [comment]
Also, I have built my distro on Mac. Thanks a lot!

**Comment by feross** [comment]
How are you guys getting this to work without the Squirrel.Windows fix which has to be built into Electron? Are you compiling Electron?

**Comment by paulcbetts** [comment]
Squirrel.Windows isn't built into Electron unlike Squirrel.Mac, it's really just a standalone executable that we shell out to. It's vendored in electron-winstaller

**Comment by feross** [comment]
Ah, gotcha. Okay. Will wait for a new `windows-installer` release with the Squirrel.Windows changes.

**Comment by feross** [comment]
Squirrel.Windows was updated, so this can be closed now.
