### ISSUE TITLE
[Windows] Options to specify version-string for setup file metadata and file name

### ISSUE THREAD

**Issue by ankitaggarwal011** [electron/windows-installer#62]
Hi,

Currently, I couldn't find any documented option to specify the version-string including ProductName, OrignalFileName for output setup file metadata and the name of the output setup file. I am using Windows 7 x64.

Is it possible to include the same with the configuration? Thanks.

**Comment by develar** [comment]
Consider to use https://github.com/electron-userland/electron-builder

**Comment by ankitaggarwal011** [comment]
@develar, I was using electron-builder, but after it's 3.0 update, I am running into a lot of problems. Thus, I thought it would be simpler to directly use electron-packager with electron-winstaller. 

The issue options wasn't available in electron-builder. Since, electron-builder uses electron-winstaller, so I guess the option has to be available over here before it can be used in electron-builder. Thanks for the help.

**Comment by MarshallOfSound** [comment]
Fixed in #60
