### ISSUE TITLE
The input package file targets no platform and cannot be transformed into a release package

### ISSUE THREAD

**Issue by peterkuma** [electron/windows-installer#63]
When building an installer on Debian stable (Debian GNU/Linux 8.3) I get
the following error:

    No dice: Failed with exit code: 255
    Output:
    System.InvalidOperationException: The input package file /mnt/data1/devel/electron-quick-start/installer/electron-quick-start.1.0.0.nupkg targets no platform and cannot be transformed into a release package.
      at Squirrel.ReleasePackage.CreateReleasePackage (System.String outputFile, System.String packagesRootDir, System.Func`2 releaseNotesProcessor, System.Action`1 contentsPostProcessHook) [0x00000] in <filename unknown>:0 
      at Squirrel.Update.Program.Releasify (System.String package, System.String targetDir, System.String packagesDir, System.String bootstrapperExe, System.String backgroundGif, System.String signingOpts, System.String baseUrl, System.String setupIcon, Boolean generateMsi) [0x00000] in <filename unknown>:0 
      at Squirrel.Update.Program.executeCommandLine (System.String[] args) [0x00000] in <filename unknown>:0 
      at Squirrel.Update.Program.main (System.String[] args) [0x00000] in <filename unknown>:0 

How to reproduce:

    git clone https://github.com/electron/electron-quick-start.git
    cd electron-quick-start
    npm install --save-dev electron-winstaller
    electron-packager . electron-quick-start --platform win32 --arch x64 --out dist --version 0.37.4 --overwrite
    node electron-winstaller.js

`electron-winstaller.js`:

    var electronInstaller = require('electron-winstaller');

    resultPromise = electronInstaller.createWindowsInstaller({
      appDirectory: 'dist/electron-quick-start-win32-x64',
      outputDirectory: 'installer',
      authors: '',
      exe: 'electron-quick-start.exe'
    });

    resultPromise.then(() => console.log("It worked!"), (e) => console.log(`No dice: ${e.message}`));

electron-packager is in version 6.0.0. mono and wine are both installed on the
system, but I am not sure if some other packages are required as well:

    mono-runtime          3.2.8+dfsg-10
    mono-devel            3.2.8+dfsg-10
    mono-4.0-gac          3.2.8+dfsg-10
    mono-utils            3.2.8+dfsg-10
    wine                  1.6.2-20
    wine32                1.6.2-20
    wine32-dev-tools      1.6.2-20
    wine32-development    1.7.29-4
    wine32-tools          1.6.2-20

`uname -a`:

    Linux localhost 4.3.0-0.bpo.1-amd64 #1 SMP Debian 4.3.5-1~bpo8+1 (2016-02-23) x86_64 GNU/Linux

**Comment by peterkuma** [comment]
The problem was likely due to an old version of mono. After upgrading to Debian stable (mono 4.2.1) this error did not appear any more. However, I have encountered the same problem as in #55 with hanging mono.

**Comment by SWortham** [comment]
I'm getting the same error, "The input package file /mnt/data1/devel/electron-quick-start/installer/electron-quick-start.1.0.0.nupkg targets no platform and cannot be transformed into a release package."  But we're on mono 4.6.0.

**Comment by andrewda** [comment]
Getting the same error with 4.8.1 on Mac.

**Comment by nadav-dav** [comment]
why is this closed? was the issue resolved?

**Comment by Marcinius** [comment]
Shouldn't be closed, get the same thing on Windows.

**Comment by fcastilloec** [comment]
I'm getting this error with mono 5.10.0.160 on Ubuntu 16.04
