### ISSUE TITLE
Squirrel throws System.OutOfMemoryException when diffing large files (160mb)

### ISSUE THREAD

**Issue by themoritz** [electron/windows-installer#73]
See https://github.com/Squirrel/Squirrel.Windows/issues/651

Probably an issue of squirrel itself, but referencing it here. Also not 100% sure that this is not caused by improper use of squirrel...

**Comment by havenchyk** [comment]
ping @paulcbetts

**Comment by develar** [comment]
Related: https://github.com/electron-userland/electron-builder/issues/464#issuecomment-223881747

**Comment by develar** [comment]
Diff algo in the Squirrel.Windows intended to load the whole file into the memory — both msdelta and bsdiff assume that you have enough memory. It is trade-off. Possible solution — use xdelta + lzma secondary compression. Or! May be it will be enough just upgrade to DeltaCompressionDotNet v2 (flag DELTA_FLAG_IGNORE_FILE_SIZE_LIMIT) —maybe msdelta consumes less memory than bsdiff.

**Comment by themoritz** [comment]
@develar or @mzmousa could you explain in more detail where and how I set that flag to switch to msdelta?

**Comment by MarshallOfSound** [comment]
This should be tracked upstream in the linked Squirrel.Windows issue

**Comment by WolfieZero** [comment]
Quick fix I found for this is deleting the directory you're writing to.
