### ISSUE TITLE
Update Squirrel.Windows

### ISSUE THREAD

**Issue by feross** [electron/windows-installer#74]
When is a new version of Squirrel.Windows coming out? Would be great to get all those fixes into our windows installer.

**Comment by havenchyk** [comment]
@feross is there a way to use git submodules here or at least git lfs?

As for topic, we need to ask @paulcbetts

**Comment by paulcbetts** [comment]
@feross I wanted to finish my staged rollouts PR but I think I'll make a release on Monday without it, then do staged rollouts next

**Comment by feross** [comment]
Excellent - thanks for all your good work.

**Comment by feross** [comment]
Fixed by https://github.com/electron/windows-installer/pull/75
