### ISSUE TITLE
Updating to `2.3.0` breaks any application with a space in its name

### ISSUE THREAD

**Issue by MarshallOfSound** [electron/windows-installer#78]
As of `2.3.0` we are using a version of `Squirrel.Windows` that "fixes" the space = "%20" bug that has been around for a while.  The problem is that some pre-existing applications  have shortcuts set up with that '%20' in the name.

This means that updating to the new naming scheme breaks existing installations as these shortcuts stop working rendering the application useless and unstartable.

Not sure where this fix should go (probably Squirrel.Windows) but posting this here to warn other users

**Comment by MarshallOfSound** [comment]
And as a side note it doesn't appear that you can un-update this patch, releasing another update using `2.2.0` to package the application still ends up with the new "fixed" exe name.  I'm guessing it applies the fix on update aswell which means that somewhere there are 134 people staring at a borked update and there is nothing I can do about it :cry:

**Comment by paulcbetts** [comment]
Ugh, this sucks, sorry @MarshallOfSound. To work around this, developers should create the shortcut in their `squirrel-updated` hook (i.e. do the same thing they are doing in the install hook)

**Comment by MarshallOfSound** [comment]
@paulcbetts Yep that's what I quickly did, but this brings up two issues still.

* Now whenever the app is updated the shortcut is brought back even if a user deliberately chose to move it or delete it
* It doesn't help with applications that have been "pinned" to the task bar as Squirrel has no knowledge of those shortcuts.

I think the fix for this is to add backwards compatibility with the old `%20` scheme.  E.g. When you receive the `--processStart` command check if the version with spaces or the version with `%20` exists and start the one that does.

**Comment by MarshallOfSound** [comment]
Also there is not yet a released version of `windows-installer` that has the https://github.com/Squirrel/Squirrel.Windows/pull/670 fix in it which is also related to this shortcut issue.

**Comment by rgoliveira** [comment]
@MarshallOfSound, it was I who opened issue https://github.com/MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-/issues/962. Today I updated to 3.2.4 and noticed the shortcut was created again, although you closed https://github.com/MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-/issues/962 on fd3ffe17a2228b929c7307bf0a00eedfcedab199.

Was this intentional as a way to fix this `%20` problem?

**Comment by MarshallOfSound** [comment]
@rgoliveira Yes, unfortunately the needs of the many outweighed the needs of the few :cry: 

The only way to get the update working was to force the shortcut upon everyone.  Once someone (maybe me) gets around to fixing this issue I will revert our code so that the shortcut doesn't keep coming back :+1:

**Comment by rgoliveira** [comment]
@MarshallOfSound I see... No big deal, just wanted to be sure :thumbsup: Hope it gets fixed soon. Cheers :beers:

**Comment by MarshallOfSound** [comment]
@paulcbetts I'm happy to keep using `2.2.0` (I don't see how I can upgrade with this issue) but is it possible to back release a `2.2.1` version with this commit https://github.com/electron/windows-installer/commit/92b1ee46829dc8c72cf9d0c17330fb04da71a752 in it?
