### ISSUE TITLE
remoteReleases Fails to Sync URL

### ISSUE THREAD

**Issue by ractoon** [electron/windows-installer#79]
When specifying a remoteReleases URL I'm receiving the following error:

````
Attemping to sync URL as remote RELEASES folder
Failed to sync URL as GitHub repo: Repo URL must be to the root URL of the repo e.g. https://github.com/myuser/myrepo
````

However, I'm not using a GitHub repo for my releases but https://github.com/ArekSredzki/electron-release-server

I've verified the URL used is returning the expected data for releases, but continue to receive this error. Is there a way to use non-GitHub release servers?

**Comment by kashban** [comment]
Ähem, why is this closed? How did you solve it?

**Comment by syonip** [comment]
How was it solved?

**Comment by ractoon** [comment]
Hi All,

This issue got resolved on the https://github.com/ArekSredzki/electron-release-server - this package worked correctly but it was my endpoint that was not working. In my case it was due to the file naming at the release server endpoint. The feed URLs are set to:

`
var feedURL = os === 'win32' ? 'https://example.com/update/win32/' + app.getVersion() + '/stable' : 'https://example.com/update/osx/' + app.getVersion();
  autoUpdater.setFeedURL(feedURL);
`

The Windows installer was not able to be downloaded due to a naming convention. Removing the "ia32" from the generated file allowed the update to be downloaded as expected. Further reading on this issue can be found here: https://github.com/ArekSredzki/electron-release-server/issues/17#issuecomment-217060801

**Comment by syonip** [comment]
Thanks.
Just solved it too. 
In my case it was missing mime type mappings for ".nupkg" and "." (no extension) files on the iis server serving the static installers folder.
