### ISSUE TITLE
Takes a long time to boot the app

### ISSUE THREAD

**Issue by mrmayfield** [electron/windows-installer#84]
The boot time on my app is pretty bad, and it shows this screen each time:
<img width="295" alt="screen shot 2016-05-08 at 9 09 46 pm" src="https://cloud.githubusercontent.com/assets/7200471/15103547/565b633c-1561-11e6-890f-f2a3f778035b.png">

What can I do to speed up the boot? It looks to me like it's installing the application before allowing it to run?

**Comment by paulcbetts** [comment]
>  It looks to me like it's installing the application before allowing it to run?

@mrmayfield Are you saying every time you start the app it shows the splash screen?

**Comment by mrmayfield** [comment]
It seems like for me yes, everytime it's showing the splash screen. It is supposed to show it only once during initial install after which point the app should boot up nearly immediately?

**Comment by KevinMartin** [comment]
What you're double-clicking on is the installer, not the actual app.

So every time you open it, the reason why it's so slow, is that it's installing the app then running it.

**Comment by mrmayfield** [comment]
And then after it's installed there should be an executable that will boot immediately? I will try and see, I'm running it on a VM and can't seem to find the installed version.

**Comment by KevinMartin** [comment]
Yes and no. The executable is hidden in `~\App Data\Local\{app name}\app-{version}` (or something like that).

When the installer is almost done running, it calls your app with a flag (`App.exe --squirrel-install`) where you should go ahead and spawn a process that runs `..\Update.exe --createShortcut` which creates the shortcuts in the start menu and desktop.

Read here: https://github.com/electron/windows-installer#user-content-handling-squirrel-events

**Comment by mrmayfield** [comment]
Ahhh I see. Okay cool, first squirrel app for me so I'm still learning, will check this out.
