### ISSUE TITLE
Huge difference in delta file size for x64

### ISSUE THREAD

**Issue by SamvelRaja** [electron/windows-installer#85]
Hi,
I had been creating the installer for both the windows ia32 and x64 arch.
For some reasons the delta file generated for my x64 architecture is too big.

For me:  size of
V1 ia32 = **43mb**,
 v1 x64 =  **96mb**

This _huge difference itself weird_ for me of same code base.

On V2 delta ia32 = **22kb**,
      v2 delta x64  =  **50mb**

Can someone help me out?

```javascript

var electronInstaller = require('electron-winstaller');

resultPromise =   electronInstaller.createWindowsInstaller({
      appDirectory: applicationDirectory,
      outputDirectory: outDirectory,
      authors: AuthurName,
      setupExe: setupExeName,
      noMsi: true,
      exe: exeName,
      remoteReleases:releaseURL 
  });

resultPromise.then(() => console.log("Installer created for "+ packageName + ' '+ channel +' '+platform),
                  (e) => console.log(`No dice: ${e.message}`));
```

**Comment by paulcbetts** [comment]
Squirrel attempts to first create a diff via msdelta and if it fails, we fall back to bsdiff/bspatch - it sounds like msdelta was able to create the delta for x86 but not for amd64, bummer. You can open the NuGet file yourself and poke around to be sure though, it's just a zip file

**Comment by SamvelRaja** [comment]
@paulcbetts It was my problem.. I was packaging the app in same folder which results in increase in the size of the package of x64 which packed after ia32. This ultimately chains for the problem for huge diff and stuffs. Sorry for disturb you guys... Appreciate your immediate response.

**Comment by paulcbetts** [comment]
nbd

**Comment by mzmousa** [comment]
@SamvelRaja what do you mean you were packaging the app in the same folder? Why would this affect the size of the delta package ?

**Comment by SamvelRaja** [comment]
@mzmousa I package the app in the same `build folder` which creates the packaged app for ia32 inside my build folder itself.. that y on packaging the x64 the file size got doubled.
