### ISSUE TITLE
file path cannot longer than 260

### ISSUE THREAD

**Issue by caibirdme** [electron/windows-installer#88]
Hi.all:
I used a lot of third party package from npm in my project, which will make the file path get very deep even longer than 260 characters and then it will emit an error.How can I fix it,THX

**Comment by mzmousa** [comment]
Try ``` npm dedupe ``` to decrease the nesting of your directories. Also, in the directory where you're creating your installer, type in this command:
``` find . -type d -print|awk '{print length($0), $0}'|sort -n|tail -10 ``` to get the lengths of the longest paths. I found that if the longest path was < 200, creating the installer worked fine. But you _need_ to make it less than 260, there is no workaround for that.

**Comment by MarshallOfSound** [comment]
@caibirdme If you update to `npm 3.x.x` this issue will probably go away.  Simply run `npm i -g npm` and then reinstall your `node_modules` directory

**Comment by caibirdme** [comment]
@MarshallOfSound I'm using npm 3.8.3,I think it's a problem of sqlite3.All the long path files come from sqlite3 module.

**Comment by caibirdme** [comment]
@mzmousa Thanks very much!! `npm dedupe` works fine.

**Comment by mzmousa** [comment]
Np.  Also what @MarshallOfSound said, upgrading to npm 3+ and reinstall your node modules, I don't think you'll need a dedupe then. But npm 3+ limits nesting in the node modules, making you not have to do a dedupe

**Comment by caibirdme** [comment]
@mzmousa I'm using npm3+ all the time...I think it might be a problem of sqlite3 that use `node-pre-gyp` to install its dependencies
