### ISSUE TITLE
Not able to include releaseNotes in nuspec file

### ISSUE THREAD

**Issue by albertsuchvi** [electron/windows-installer#95]
It seems that Squirrel.Windows v1.4.0 ignores nupkgs that do not include a <releaseNotes> element in the nuspec file (https://github.com/Squirrel/Squirrel.Windows/commit/c1bd22e7a89d534848c64cf3686d4389bb8a69e0), but electron-winstaller does not allow to set this element, so teh packages generated are being ingored by Squirrel

**Comment by paulcbetts** [comment]
I'm not sure you're reading the intent of this commit right, this commit just makes us ignore release notes when calling `FetchReleaseNotes`

**Comment by albertsuchvi** [comment]
I may not be understanding the code correctly, but by returning 
`return Enumerable.Empty<Tuple<ReleaseEntry, string>>();` (line 54) when release notes are not available, aren't releases that do not have release notes effectively removed from the list of available reelases?
Shoudn't yo ratrher do something like:
`return EnumerableExtensions.Return(Tuple.Create(x, String.Empty));`
to add an entry with the release that does not have release notes?
Thanks

**Comment by MarshallOfSound** [comment]
Hey 👋 

This issue is being closed as it is stale.  This normally means that the issue has been fixed in newer versions or this issue or no longer impacting you.  If this is not the case please feel free to comment with and @ mention me and we can revisit this.
