### ISSUE TITLE
Start menu entry and shortcut name is GitHub / Electron

### ISSUE THREAD

**Issue by lexun** [electron/windows-installer#97]
In spite of providing an owner, title, and id, I'm getting this in my start menu:

![image](https://cloud.githubusercontent.com/assets/1910143/15698937/11c73f8c-277e-11e6-9e97-12ca984dd399.png)

And this on my desktop:

![image](https://cloud.githubusercontent.com/assets/1910143/15698974/5004aff0-277e-11e6-92e3-c664d6d4a94b.png)

This is the `.nuspec` that is being generated when using this package:

```xml
<?xml version="1.0"?>
<package xmlns="http://schemas.microsoft.com/packaging/2011/08/nuspec.xsd">
  <metadata>
    <id>cuemu-launcher</id>
    <version>0.10.0</version>
    <title>Launcher</title>
    <authors>CUEmu</authors>
    <owners>CUEmu</owners>
    <iconUrl>https://raw.githubusercontent.com/atom/electron/master/atom/browser/resources/win/atom.ico</iconUrl>
    <requireLicenseAcceptance>false</requireLicenseAcceptance>
    <description>Patcher and Launcher for the CUEmu project.</description>
    <copyright>Copyright © 2016 CUEmu</copyright>
  </metadata>
</package>
```

It might be worth noting that the application shows up the way I'm expecting in the Add / Remove programs section of the Windows Control Panel:

![image](https://cloud.githubusercontent.com/assets/1910143/15699084/1c0aadca-277f-11e6-916d-d375a94c3e86.png)

I'm generating the installer on OSX and testing it on Windows 10.

Please let me know if there is any other information that would be helpful, and I apologize in advance if the issue is related to another package or my lack of understanding.

Thank you.

**Comment by MarshallOfSound** [comment]
You need to use https://github.com/electron-userland/electron-packager/blob/master/docs/api.md#version-string when packaging

**Comment by lexun** [comment]
Thank you very much for the fast response! That looks like exactly what I needed.

**Comment by develar** [comment]
@lexun Or just use https://github.com/electron-userland/electron-builder :) to be free of low-level details under the hood.

**Comment by Tobyheiam** [comment]
> You need to use https://github.com/electron-userland/electron-packager/blob/master/docs/api.md#version-string when packaging

It seems that 'version-string' becomes 'win32metadata' now.
https://github.com/electron/electron-packager/blob/master/docs/api.md#win32metadata
