### ISSUE TITLE
Step by step installer

### ISSUE THREAD

**Issue by yeluoqiuzhi** [electron/windows-installer#99]
I want a step by step installer, user can click next and next to install,but I found this package this is no installer GUI, is it normal?Is it  installing at background? It sometimes take very long time. oh,god.

**Comment by MarshallOfSound** [comment]
@yeluoqiuzhi It is completely by design.  You can read more about it over at https://github.com/Squirrel/Squirrel.Windows

> Installing is Wizard-Free™, with no UAC dialogs, does not require reboot, and is .NET Framework friendly.

**Comment by yeluoqiuzhi** [comment]
Thank you, I got it.

**Comment by gasparyanyur** [comment]
@yeluoqiuzhi Please tell me how you could solve the problem?
